# Share 5 - BAG
## Salmonellosis
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/data

Werden monatlich geupdatet

Obligatorische Meldung

In [13]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [14]:
# Daten laden --> read_csv / read_excel
# Falls mehrere sheets --> sheet_name="sheet"


data = pd.read_csv("data/salmonellosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Variablen

In [15]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

* valueCategory: Was gemessen wird --> Hier: Anzahl gemeldete Fälle
* temporal: Welcher Zeitabschnitt --> Jahr und Monat
* temporal_type: Typ der Zeit --> Monat
* georegion: Kanton oder Land --> hier Anfang Land später Kanton
* georegion_type: Typ der Georegion --> Land/Kantonal
* agegroup: Alterskategorie
* agegroup_type: Zuordnung zur Oberthema --> bei allen gleich
* sex: Geschlecht
* value: Wert basierend auf vorhergehende Kategorien
* pop: Bevölkerung zum Zeitpunkt der Erhebung
* incValue: neuaufgetrettene Fälle innerhalb der Gruppe und Zeit
* valueYearCumSum: Gesamter Wert über das Jahr
* valueMean3y: Durchschnittswert der letzten drei Jahre
* trend: ist der Trend abnehmend(falling), gleich(stagnant) oder steigend(rising)
* prct: prozentualer Anteil der Fälle in den Kategorien und Zeiteinheit
* deltaValue: Unterschied des value zum vorherigen Wert
* deltaIncValue: Unterschied des incValue zum vorherigen Wert
* incValuePrctChange: Prozentualer Unterschied zum vorherigen Wert
* valueMean5y: Durchschnittlicher Wert der letzten 5 Jahre
* dataComplete: ist dieser Datenpunkt komplett

In [16]:
data.dtypes

valueCategory          object
temporal               object
temporal_type          object
georegion              object
georegion_type         object
agegroup               object
agegroup_type          object
sex                    object
type                   object
value                 float64
pop                   float64
incValue              float64
valueYearCumSum       float64
valueMean3y           float64
trend                  object
prct                  float64
deltaValue            float64
deltaIncValue         float64
incValuePrctChange    float64
valueMean5y           float64
dataComplete             bool
dtype: object

### Entfernen der Mediane

--> Die Durchschnittswerte sind als Einzelne Datenpunkte erhoben

In [17]:
data_def = data[data["valueCategory"] == "cases"]

data_def

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,monophasic_salmonella_typhimurium,111.0,...,1.22,NaN,136.0,NaN,4.9,NaN,NaN,NaN,NaN,True
786,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,napoli,63.0,...,0.69,NaN,54.3,NaN,2.8,NaN,NaN,NaN,NaN,True
787,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,other,759.0,...,8.35,NaN,590.7,NaN,33.2,NaN,NaN,NaN,NaN,True
788,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,species,170.0,...,1.87,NaN,295.7,NaN,7.4,NaN,NaN,NaN,NaN,True
789,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,typhimurium,360.0,...,3.96,NaN,308.7,NaN,15.7,NaN,NaN,NaN,NaN,True

### Visuelle Analyse

In [18]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Salmonellosis Georegion 2013-2025"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

* ZH am höchsten --> grösster Kanton
* kleine Kantone --> weniger Fälle

In [19]:
#Gruppieren nach georegion und Werte summieren
counts = (
    data_def.groupby("temporal")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_temporal = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("sum_value", title="Cases")
).properties(
    title="Salmonellosis Temporal"
)

# Textlabels
text = bar_temporal.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_temporal = bar_temporal + text
bar_temporal

alt.LayerChart(...)

* Datensatz aufteilen in monatlich und Jährlich

In [20]:
data_1 = data_def.copy()

data_year = data_1[data_1["temporal_type"] == "year"]

data_year

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,86.0,...,13.51,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,11.0,...,20.49,NaN,NaN,NaN,0.9,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,141.0,...,14.08,NaN,NaN,NaN,11.1,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,47.0,...,16.87,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,monophasic_salmonella_typhimurium,111.0,...,1.22,NaN,136.0,NaN,4.9,NaN,NaN,NaN,NaN,True
786,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,napoli,63.0,...,0.69,NaN,54.3,NaN,2.8,NaN,NaN,NaN,NaN,True
787,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,other,759.0,...,8.35,NaN,590.7,NaN,33.2,NaN,NaN,NaN,NaN,True
788,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,species,170.0,...,1.87,NaN,295.7,NaN,7.4,NaN,NaN,NaN,NaN,True
789,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,typhimurium,360.0,...,3.96,NaN,308.7,NaN,15.7,NaN,NaN,NaN,NaN,True

In [21]:
# Ohne Kantone
data_year_CH = data_year[data_year["georegion"].isin(["CH", "CHFL"])]

bar_year = alt.Chart(data_year_CH).mark_bar().encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("value", title="Cases")
).properties(
    title="Salmonellosis Year"
)

bar_year

alt.Chart(...)

* Steigende Fallzahlen in den letzten Jahren

In [22]:
data_2 = data_def.copy()

data_month = data_2[data_2["temporal_type"] == "month"]

data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,141.0,...,1.55,472.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,126.0,...,1.39,598.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,170.0,...,1.87,768.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,290.0,...,3.19,1058.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,555.0,...,6.10,1613.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True

In [23]:
bar_month = alt.Chart(data_month).mark_bar().encode(
    x=alt.X("temporal:N", title="Temporal"),
    y=alt.Y("value:Q", title="Cases"),
    color=alt.Color("trend:N")
).properties(
    title="Salmonellosis Month"
)

bar_month

alt.Chart(...)

* im Sommer am Höchsten¨
* im Winter tiefer
* steigende Zahlen in den letzten Jahren