# Share 5 - BAG
## Salmonellosis
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/data

Werden monatlich geupdatet

Obligatorische Meldung

In [474]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [475]:
# Daten laden --> read_csv / read_excel
# Falls mehrere sheets --> sheet_name="sheet"


data = pd.read_csv("data/salmonellosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Variablen

In [476]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

* valueCategory: Was gemessen wird --> Hier: Anzahl gemeldete Fälle
* temporal: Welcher Zeitabschnitt --> Jahr und Monat
* temporal_type: Typ der Zeit --> Monat
* georegion: Kanton oder Land --> hier Anfang Land später Kanton
* georegion_type: Typ der Georegion --> Land/Kantonal
* agegroup: Alterskategorie
* agegroup_type: Zuordnung zur Oberthema --> bei allen gleich
* sex: Geschlecht
* value: Wert basierend auf vorhergehende Kategorien
* pop: Bevölkerung zum Zeitpunkt der Erhebung
* incValue: Fälle auf 100'000 Personen
* valueYearCumSum: Gesamter Wert über das Jahr
* valueMean3y: Durchschnittswert der letzten drei Jahre
* trend: ist der Trend abnehmend(falling), gleich(stagnant) oder steigend(rising)
* prct: prozentualer Anteil der Fälle in den Kategorien und Zeiteinheit
* deltaValue: Unterschied des value zum vorherigen Wert
* deltaIncValue: Unterschied des incValue zum vorherigen Wert
* incValuePrctChange: Prozentualer Unterschied zum vorherigen Wert
* valueMean5y: Durchschnittlicher Wert der letzten 5 Jahre
* dataComplete: ist dieser Datenpunkt komplett

In [477]:
data.dtypes

valueCategory          object
temporal               object
temporal_type          object
georegion              object
georegion_type         object
agegroup               object
agegroup_type          object
sex                    object
type                   object
value                 float64
pop                   float64
incValue              float64
valueYearCumSum       float64
valueMean3y           float64
trend                  object
prct                  float64
deltaValue            float64
deltaIncValue         float64
incValuePrctChange    float64
valueMean5y           float64
dataComplete             bool
dtype: object

### Datensatz für Cases

--> Die Durchschnittswerte sind als Einzelne Datenpunkte erhoben

In [478]:
data_def = data[data["valueCategory"] == "cases"]
data_def = data[data["type"] == "all"]

data_def

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Datensatz für Agegroup

In [515]:
data_med = data[~data["agegroup"].isin(["all"])]

data_med

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
790,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,31.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
791,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
792,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,12.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
793,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
794,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,17.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
795,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
796,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,31.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
797,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
798,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,12.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
799,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
800,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,18.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
801,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
802,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,33.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
803,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,23.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
804,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,13.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
805,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
806,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,19.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
807,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
808,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,35.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
809,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,24.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
810,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,14.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
811,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,13.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
812,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
813,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [480]:
# Exportieren des Datensatzes für Fälle pro Altersklasse
# data_med.to_csv("./export/data_salmonellosis_fälle_altersklasse.csv", index=False)

### Datensatz für Geschlecht

In [512]:
data_sex = data[~data["sex"].isin(["all"])]

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
814,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,all,7169.0,...,NaN,NaN,NaN,NaN,48.4,NaN,NaN,NaN,NaN,True
815,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,all,7628.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
816,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,all,15.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
817,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,all,7444.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
818,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,all,7906.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
819,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,all,14.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
820,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,all,7985.0,...,NaN,NaN,NaN,NaN,48.7,NaN,NaN,NaN,NaN,True
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [482]:
# Exportieren des Datensatzes für Fälle Geschlechterverteilung
# data_sex.to_csv("./export/data_salmonellosis_fälle_geschlecht.csv", index=False)

### Datensatz für Type

In [509]:
# Nur Variablen mit Types --> ~
data_types = data[~data["type"].isin(["all"])]
data_types

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
712,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,enteritidis,366.0,...,4.48,NaN,NaN,NaN,28.8,NaN,NaN,NaN,NaN,True
713,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,monophasic_salmonella_typhimurium,204.0,...,2.49,NaN,NaN,NaN,16.1,NaN,NaN,NaN,NaN,True
714,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,napoli,17.0,...,0.21,NaN,NaN,NaN,1.3,NaN,NaN,NaN,NaN,True
715,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,other,467.0,...,5.71,NaN,NaN,NaN,36.7,NaN,NaN,NaN,NaN,True
716,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,species,17.0,...,0.21,NaN,NaN,NaN,1.3,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,monophasic_salmonella_typhimurium,111.0,...,1.22,NaN,136.0,NaN,4.9,NaN,NaN,NaN,NaN,True
786,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,napoli,63.0,...,0.69,NaN,54.3,NaN,2.8,NaN,NaN,NaN,NaN,True
787,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,other,759.0,...,8.35,NaN,590.7,NaN,33.2,NaN,NaN,NaN,NaN,True
788,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,species,170.0,...,1.87,NaN,295.7,NaN,7.4,NaN,NaN,NaN,NaN,True
789,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,typhimurium,360.0,...,3.96,NaN,308.7,NaN,15.7,NaN,NaN,NaN,NaN,True

In [ ]:
# Exportieren des Datensatzes für Fälle nach Type
# data_types.to_csv("./export/data_salmonellosis_fälle_type.csv", index=False)

### Visuelle Analyse

In [484]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Salmonellosis Georegion 2013-2025"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

* ZH am höchsten --> grösster Kanton
* kleine Kantone --> weniger Fälle

In [485]:
# nur 2025
data_cantons_2025 = data_cantons[data_cantons["temporal"] == "2025"]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons_2025.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion_2025 = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Salmonellosis Georegion 2025"
)

# Textlabels
text = bar_georegion_2025.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion_2025 = bar_georegion_2025 + text
bar_georegion_2025

alt.LayerChart(...)

In [486]:
#Gruppieren nach georegion und Werte summieren
counts = (
    data_def.groupby("temporal")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_temporal = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("sum_value", title="Cases")
).properties(
    title="Salmonellosis Temporal"
)

# Textlabels
text = bar_temporal.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_temporal = bar_temporal + text
bar_temporal

alt.LayerChart(...)

* Datensatz aufteilen in monatlich und Jährlich

In [487]:
data_1 = data_def.copy()

data_year = data_1[data_1["temporal_type"] == "year"]

data_year

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,86.0,...,13.51,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,11.0,...,20.49,NaN,NaN,NaN,0.9,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,141.0,...,14.08,NaN,NaN,NaN,11.1,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,47.0,...,16.87,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [488]:
# Exportieren des Datensatzes für Fälle pro Kanton
# data_year.to_csv("./export/data_salmonellosis_fälle_georegion.csv", index=False)

In [489]:
# Ohne Kantone
data_year_CH = data_year[data_year["georegion"].isin(["CH"])]

bar_year = alt.Chart(data_year_CH).mark_bar().encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("value", title="Cases")
).properties(
    title="Salmonellosis Year"
)

# Textlabels
text = bar_year.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_year = bar_year + text
bar_year

alt.LayerChart(...)

* Steigende Fallzahlen in den letzten Jahren

In [490]:
data_2 = data_def.copy()

data_month = data_2[data_2["temporal_type"] == "month"]

data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,max_value_10y,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,141.0,...,1.55,499.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
328,max_value_10y,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,177.0,...,1.95,676.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
329,max_value_10y,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,180.0,...,1.98,856.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
330,max_value_10y,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,290.0,...,3.19,1102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
331,max_value_10y,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,555.0,...,6.10,1613.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [491]:
# Exportieren des Datensatzes für Fälle pro Monat
# data_month.to_csv("./export/data_salmonellosis_fälle_monat.csv", index=False)

In [492]:
data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,max_value_10y,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,141.0,...,1.55,499.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
328,max_value_10y,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,177.0,...,1.95,676.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
329,max_value_10y,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,180.0,...,1.98,856.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
330,max_value_10y,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,290.0,...,3.19,1102.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
331,max_value_10y,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,555.0,...,6.10,1613.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [493]:
#Gruppieren nach Jahren und Werte summieren
counts = (
    data_month.groupby("temporal")
        .agg(sum_value=("value", "sum"), trend = ("trend", "first"))
        .reset_index()
)

bar_month = alt.Chart(counts).mark_bar().encode(
    x=alt.X("temporal:N", title="Temporal"),
    y=alt.Y("sum_value:Q", title="Cases"),
    color=alt.Color("trend:N")
).properties(
    title="Salmonellosis Month"
)

# Textlabels
text = bar_month.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

bar_month = bar_month + text
bar_month

alt.LayerChart(...)

* im Sommer am Höchsten¨
* im Winter tiefer
* steigende Zahlen in den letzten Jahren

In [494]:
bar_age = alt.Chart(data_med).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Salmonellosis Altersgruppen 2022 - 2025"
)

bar_age

alt.Chart(...)

In [495]:
data_age_2025 = data_med[data_med["temporal"] == "2025"]

bar_age_2 = alt.Chart(data_age_2025).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases")
).properties(
    title="Salmonellosis Altersgruppen 2025"
)

# Textlabels
text = bar_age_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="incValue:Q"
)

bar_age_2 = bar_age_2 + text

bar_age_2

alt.LayerChart(...)

In [496]:
bar_sex = alt.Chart(data_sex).mark_bar().encode(
    x=alt.X("sex", title="Sex"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Salmonellosis Geschlechterverteilung 2022 - 2025"
)

bar_sex

alt.Chart(...)

In [518]:
data_sex_2025 = data_sex[data_sex["temporal"] == "2025"]

bar_sex_2 = alt.Chart(data_sex_2025).mark_bar().encode(
    x=alt.X("sex", title="Geschlecht"),
    y=alt.Y("value", title="Cases")
).properties(
    title="Salmonellosis Geschlechterverteilung 2025"
)

# Textlabels
text = bar_sex_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_sex_2 = bar_sex_2 + text
bar_sex_2

alt.LayerChart(...)

In [526]:
bar_types = alt.Chart(data_types).mark_bar().encode(
    x=alt.X("type", title="Typ"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Salmonellosis Types 2013-2025"
)


bar_types

alt.Chart(...)

In [542]:
bar_types = alt.Chart(data_types).mark_point().encode(
    x=alt.X("type", title="Typ"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Salmonellosis Types 2013-2025"
)

# Textlabels
text = bar_types.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_types = bar_types + text
bar_types


bar_types

alt.LayerChart(...)

In [ ]:
data_types_2025 = data_types[data_types["temporal"] == "2025"]

bar_types_2 = alt.Chart(data_types_2025).mark_bar().encode(
    x=alt.X("type", title="Typ"),
    y=alt.Y("value", title="Cases")
).properties(
    title="Salmonellosis Types 2025"
)

# Textlabels
text = bar_types_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_types_2 = bar_types_2 + text
bar_types_2

alt.LayerChart(...)

### Durchschnittsberechnungen & -visualisierungen

In [498]:
#Gruppieren nach georegion und Werte summieren
counts_mean = (
    data_cantons.groupby("georegion")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts_mean).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("mean_value", title="Mean Cases")
).properties(
    title="Salmonellosis Georegion 2013-2025 Mean"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

In [499]:
# Jahr und Monat trennen
data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)

data_month

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_26628/2880901401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_26628/2880901401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete,year,month
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M01
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M02
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M03
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True,2013,M04
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True,2013,M05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,max_value_10y,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,141.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2026,M04
328,max_value_10y,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,177.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2026,M05
329,max_value_10y,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,180.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2026,M06
330,max_value_10y,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,290.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2026,M07
331,max_value_10y,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,555.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2026,M08

In [500]:
counts_mean = (
    data_month.groupby("month")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

bar_month = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("month:N", title="Month"),
    y=alt.Y("mean_value:Q", title="Cases")
).properties(
    title="Salmonellosis Month 2013-2026 Mean"
)

# Textlabels
text = bar_month.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_month = bar_month + text
bar_month

alt.LayerChart(...)

In [501]:
counts_mean = (
    data_med.groupby("agegroup")
        .agg(mean_value=("incValue", "mean")).round(0)
        .reset_index()
)

bar_age = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("mean_value", title="Cases")
).properties(
    title="Salmonellosis Altersgruppen 2022 - 2025 Mean IncValue"
)

# Textlabels
text = bar_age.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_age = bar_age + text
bar_age

alt.LayerChart(...)

In [517]:
counts_mean = (
    data_sex.groupby("sex")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

bar_sex = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("sex", title="Sex"),
    y=alt.Y("mean_value", title="Cases")
).properties(
    title="Salmonellosis Geschlechterverteilung 2022 - 2025 Mean"
)

# Textlabels
text = bar_sex.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_sex = bar_sex + text
bar_sex

bar_sex

alt.LayerChart(...)

### Auf 100'000 Personen gerechnet

In [503]:
data_cantons

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,86.0,...,13.51,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,11.0,...,20.49,NaN,NaN,NaN,0.9,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,141.0,...,14.08,NaN,NaN,NaN,11.1,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,47.0,...,16.87,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,cases,2025,year,UR,canton,all,agegroup_food,all,all,12.0,...,31.35,NaN,9.0,NaN,0.5,NaN,NaN,NaN,NaN,True
708,cases,2025,year,VD,canton,all,agegroup_food,all,all,309.0,...,36.14,NaN,278.7,NaN,13.6,NaN,NaN,NaN,NaN,True
709,cases,2025,year,VS,canton,all,agegroup_food,all,all,103.0,...,27.74,NaN,89.0,NaN,4.5,NaN,NaN,NaN,NaN,True
710,cases,2025,year,ZG,canton,all,agegroup_food,all,all,21.0,...,15.70,NaN,24.0,NaN,0.9,NaN,NaN,NaN,NaN,True
711,cases,2025,year,ZH,canton,all,agegroup_food,all,all,341.0,...,21.05,NaN,349.3,NaN,15.0,NaN,NaN,NaN,NaN,True

In [504]:
data_cantons_100 = data_cantons.copy()

# Wert pro 100000 einfügen
data_cantons_100["value_100000"] = data_cantons_100["value"] / data_cantons_100["pop"] * 100000

data_cantons_100["value_100000"] = data_cantons_100["value_100000"].round(1)

data_cantons_100

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete,value_100000
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,86.0,...,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,True,13.5
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True,0.0
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,11.0,...,NaN,NaN,NaN,0.9,NaN,NaN,NaN,NaN,True,20.5
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,141.0,...,NaN,NaN,NaN,11.1,NaN,NaN,NaN,NaN,True,14.1
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,47.0,...,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN,True,16.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,cases,2025,year,UR,canton,all,agegroup_food,all,all,12.0,...,NaN,9.0,NaN,0.5,NaN,NaN,NaN,NaN,True,31.4
708,cases,2025,year,VD,canton,all,agegroup_food,all,all,309.0,...,NaN,278.7,NaN,13.6,NaN,NaN,NaN,NaN,True,36.1
709,cases,2025,year,VS,canton,all,agegroup_food,all,all,103.0,...,NaN,89.0,NaN,4.5,NaN,NaN,NaN,NaN,True,27.7
710,cases,2025,year,ZG,canton,all,agegroup_food,all,all,21.0,...,NaN,24.0,NaN,0.9,NaN,NaN,NaN,NaN,True,15.7
711,cases,2025,year,ZH,canton,all,agegroup_food,all,all,341.0,...,NaN,349.3,NaN,15.0,NaN,NaN,NaN,NaN,True,21.0

In [516]:
# nur 2025
data_cantons_100_2025 = data_cantons_100[data_cantons_100["temporal"] == "2025"]

#Bar Chart
bar_georegion = alt.Chart(data_cantons_100_2025).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("value_100000", title="Mean Cases")
).properties(
    title="Salmonellosis Georegion 2025 pro 100000"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value_100000:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)