# Share 5 - BAG
## Campylobacteriosis
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/campylobacteriosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/campylobacteriosis/data

Werden monatlich geupdatet

Obligatorische Meldung

In [105]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [106]:
# Daten laden --> read_csv / read_excel
# Falls mehrere sheets --> sheet_name="sheet"


data = pd.read_csv("data/campylobacteriosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

### Variablen

In [107]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'value', 'pop',
       'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

* valueCategory: Was gemessen wird --> Hier: Anzahl gemeldete Fälle
* temporal: Welcher Zeitabschnitt --> Jahr und Monat
* temporal_type: Typ der Zeit --> Monat
* georegion: Kanton oder Land --> hier Anfang Land später Kanton
* georegion_type: Typ der Georegion --> Land/Kantonal
* agegroup: Alterskategorie
* agegroup_type: Zuordnung zur Oberthema --> bei allen gleich
* sex: Geschlecht
* value: Wert basierend auf vorhergehende Kategorien
* pop: Bevölkerung zum Zeitpunkt der Erhebung
* incValue: neuaufgetrettene Fälle innerhalb der Gruppe und Zeit
* valueYearCumSum: Gesamter Wert über das Jahr
* valueMean3y: Durchschnittswert der letzten drei Jahre
* trend: ist der Trend abnehmend(falling), gleich(stagnant) oder steigend(rising)
* prct: prozentualer Anteil der Fälle in den Kategorien und Zeiteinheit
* deltaValue: Unterschied des value zum vorherigen Wert
* deltaIncValue: Unterschied des incValue zum vorherigen Wert
* incValuePrctChange: Prozentualer Unterschied zum vorherigen Wert
* valueMean5y: Durchschnittlicher Wert der letzten 5 Jahre
* dataComplete: ist dieser Datenpunkt komplett

In [108]:
data.dtypes

valueCategory          object
temporal               object
temporal_type          object
georegion              object
georegion_type         object
agegroup               object
agegroup_type          object
sex                    object
value                 float64
pop                   float64
incValue              float64
valueYearCumSum       float64
valueMean3y           float64
trend                  object
prct                  float64
deltaValue            float64
deltaIncValue         float64
incValuePrctChange    float64
valueMean5y           float64
dataComplete             bool
dtype: object

### Datensatz für Cases

--> Die Durchschnittswerte sind als Einzelne Datenpunkte erhoben

In [109]:
data_def = data[data["valueCategory"] == "cases"]

data_def

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,cases,2025,year,UR,canton,all,agegroup_food,all,20.0,38275.0,52.25,NaN,23.3,NaN,0.2,NaN,NaN,NaN,NaN,True
715,cases,2025,year,VD,canton,all,agegroup_food,all,1040.0,855106.0,121.62,NaN,952.7,NaN,12.0,NaN,NaN,NaN,NaN,True
716,cases,2025,year,VS,canton,all,agegroup_food,all,507.0,371288.0,136.55,NaN,462.0,NaN,5.8,NaN,NaN,NaN,NaN,True
717,cases,2025,year,ZG,canton,all,agegroup_food,all,116.0,133739.0,86.74,NaN,107.3,NaN,1.3,NaN,NaN,NaN,NaN,True
718,cases,2025,year,ZH,canton,all,agegroup_food,all,1379.0,1620020.0,85.12,NaN,1187.3,NaN,15.9,NaN,NaN,NaN,NaN,True

### Datensatz für Agegroup

In [110]:
data_med = data[data["valueCategory"] == "cases_10y_mean"]

data_med

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
719,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,66.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
720,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,129.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
721,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,79.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
722,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,75.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
723,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,102.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
724,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
725,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,64.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
726,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,125.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
727,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,77.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
728,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,74.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
729,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,102.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
730,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
731,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,63.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
732,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,124.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
733,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,76.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
734,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,75.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
735,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,104.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
736,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
737,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,63.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
738,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,124.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
739,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,77.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
740,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,76.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
741,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,108.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
742,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [111]:
# Exportieren des Datensatzes für Fälle pro Altersklasse
# data_med.to_csv("./export/data_campylobacteriosis_fälle_altersklasse.csv", index=False)

### Datensatz für Geschlecht

In [112]:
data_sex = data[data["valueCategory"] == "cases_10y_cumsum"]

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
743,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,32962.0,NaN,NaN,NaN,NaN,NaN,45.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,39264.0,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,NaN,NaN,True
745,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,528.0,NaN,NaN,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
746,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,32486.0,NaN,NaN,NaN,NaN,NaN,45.1,NaN,NaN,NaN,NaN,True
747,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,39009.0,NaN,NaN,NaN,NaN,NaN,54.2,NaN,NaN,NaN,NaN,True
748,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,492.0,NaN,NaN,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
749,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,32688.0,NaN,NaN,NaN,NaN,NaN,44.9,NaN,NaN,NaN,NaN,True
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [113]:
# Exportieren des Datensatzes für Fälle Geschlechterverteilung
# data_sex.to_csv("./export/data_campylobacteriosis_fälle_geschlecht.csv", index=False)

### Visuelle Analyse

In [ ]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Campylobacteriosis Georegion 2013-2025"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

* ZH am höchsten --> grösster Kanton
* kleine Kantone --> weniger Fälle

In [ ]:
# nur 2025
data_cantons_2025 = data_cantons[data_cantons["temporal"] == "2025"]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons_2025.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion_2025 = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Campylobacteriosis Georegion 2025"
)

# Textlabels
text = bar_georegion_2025.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion_2025 = bar_georegion_2025 + text
bar_georegion_2025

alt.LayerChart(...)

In [ ]:
data_1 = data_def.copy()

data_year = data_1[data_1["temporal_type"] == "year"]

data_year

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,546.0,636362.0,85.80,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,25.0,15778.0,158.45,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,52.0,53691.0,96.85,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,958.0,1001281.0,95.68,NaN,NaN,NaN,12.8,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,417.0,278656.0,149.65,NaN,NaN,NaN,5.6,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,cases,2025,year,UR,canton,all,agegroup_food,all,20.0,38275.0,52.25,NaN,23.3,NaN,0.2,NaN,NaN,NaN,NaN,True
715,cases,2025,year,VD,canton,all,agegroup_food,all,1040.0,855106.0,121.62,NaN,952.7,NaN,12.0,NaN,NaN,NaN,NaN,True
716,cases,2025,year,VS,canton,all,agegroup_food,all,507.0,371288.0,136.55,NaN,462.0,NaN,5.8,NaN,NaN,NaN,NaN,True
717,cases,2025,year,ZG,canton,all,agegroup_food,all,116.0,133739.0,86.74,NaN,107.3,NaN,1.3,NaN,NaN,NaN,NaN,True
718,cases,2025,year,ZH,canton,all,agegroup_food,all,1379.0,1620020.0,85.12,NaN,1187.3,NaN,15.9,NaN,NaN,NaN,NaN,True

In [ ]:
# Exportieren des Datensatzes für Fälle pro Kanton
# data_year.to_csv("./export/data_campylobacteriosis_fälle_georegion.csv", index=False)

In [ ]:
# Ohne Kantone
data_year_CH = data_year[data_year["georegion"].isin(["CH"])]

bar_year = alt.Chart(data_year_CH).mark_bar().encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("value", title="Cases")
).properties(
    title="Campylobacteriosis Year"
)

# Textlabels
text = bar_year.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_year = bar_year + text
bar_year

alt.LayerChart(...)

* Steigende Fallzahlen in den letzten Jahren

In [ ]:
data_2 = data_def.copy()

data_month = data_2[data_2["temporal_type"] == "month"]

data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,563.0,9091674.0,6.19,2252.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,851.0,9091674.0,9.36,3103.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,1096.0,9091674.0,12.05,4199.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,1280.0,9091674.0,14.08,5479.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,1392.0,9091674.0,15.31,6871.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True

In [ ]:
# Exportieren des Datensatzes für Fälle pro Monat
# data_month.to_csv("./export/data_campylobacteriosis_fälle_monat.csv", index=False)

In [ ]:
#Gruppieren nach Jahren und Werte summieren
counts = (
    data_month.groupby("temporal")
        .agg(sum_value=("value", "sum"), trend = ("trend", "first"))
        .reset_index()
)

bar_month = alt.Chart(counts).mark_bar().encode(
    x=alt.X("temporal:N", title="Temporal"),
    y=alt.Y("sum_value:Q", title="Cases"),
    color=alt.Color("trend:N")
).properties(
    title="Campylobacteriosis Month"
)

# Textlabels
text = bar_month.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

bar_month = bar_month + text
bar_month

alt.LayerChart(...)

* im Sommer am Höchsten¨
* im Winter tiefer
* steigende Zahlen in den letzten Jahren

In [ ]:
bar_age = alt.Chart(data_med).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Campylobacteriosis Altersgruppen 2022 - 2025"
)

bar_age

alt.Chart(...)

In [ ]:
data_age_2025 = data_med[data_med["temporal"] == "2025"]

bar_age_2 = alt.Chart(data_age_2025).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases")
).properties(
    title="Campylobacteriosis Altersgruppen 2025"
)

# Textlabels
text = bar_age_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="incValue:Q"
)

bar_age_2 = bar_age_2 + text

bar_age_2

alt.LayerChart(...)

In [ ]:
bar_sex = alt.Chart(data_sex).mark_bar().encode(
    x=alt.X("sex", title="Sex"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Campylobacteriosis Geschlechterverteilung 2022 - 2025"
)

bar_sex

alt.Chart(...)

In [ ]:
data_sex_2025 = data_sex[data_sex["temporal"] == "2025"]

bar_sex_2 = alt.Chart(data_sex_2025).mark_bar().encode(
    x=alt.X("sex", title="Geschlecht"),
    y=alt.Y("value", title="Cases")
).properties(
    title="Campylobacteriosis Geschlechterverteilung 2025"
)

# Textlabels
text = bar_sex_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_sex_2 = bar_sex_2 + text
bar_sex_2

alt.LayerChart(...)

### Durchschnittsberechnungen & -visualisierungen

In [ ]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts_mean = (
    data_cantons.groupby("georegion")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts_mean).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("mean_value", title="Mean Cases")
).properties(
    title="Campylobacteriosis Georegion 2013-2025 Mean"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

In [ ]:
# Jahr und Monat trennen
data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)

data_month

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_27492/2880901401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_27492/2880901401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,...,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete,year,month
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M01
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M02
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M03
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,...,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True,2013,M04
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2013,M05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,563.0,9091674.0,...,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True,2026,M04
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,851.0,9091674.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M05
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,1096.0,9091674.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M06
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,1280.0,9091674.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M07
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,1392.0,9091674.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M08

In [ ]:
counts_mean = (
    data_month.groupby("month")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

bar_month = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("month:N", title="Month"),
    y=alt.Y("mean_value:Q", title="Cases")
).properties(
    title="Campylobacteriosis Month 2013-2026 Mean"
)

# Textlabels
text = bar_month.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_month = bar_month + text
bar_month

alt.LayerChart(...)

In [ ]:
counts_mean = (
    data_med.groupby("agegroup")
        .agg(mean_value=("incValue", "mean")).round(0)
        .reset_index()
)

bar_age = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("mean_value", title="Cases")
).properties(
    title="Campylobacteriosis Altersgruppen 2022 - 2025 Mean IncValue"
)

# Textlabels
text = bar_age.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_age = bar_age + text
bar_age

alt.LayerChart(...)

In [ ]:
counts_mean = (
    data_sex.groupby("sex")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

bar_sex = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("sex", title="Sex"),
    y=alt.Y("mean_value", title="Cases")
).properties(
    title="Campylobacteriosis Geschlechterverteilung 2022 - 2025 Mean"
)

# Textlabels
text = bar_sex.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_sex = bar_sex + text
bar_sex

bar_sex

alt.LayerChart(...)

### Auf 100'000 Personen gerechnet

In [ ]:
data_cantons

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,546.0,636362.0,85.80,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,25.0,15778.0,158.45,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,52.0,53691.0,96.85,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,958.0,1001281.0,95.68,NaN,NaN,NaN,12.8,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,417.0,278656.0,149.65,NaN,NaN,NaN,5.6,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,cases,2025,year,UR,canton,all,agegroup_food,all,20.0,38275.0,52.25,NaN,23.3,NaN,0.2,NaN,NaN,NaN,NaN,True
715,cases,2025,year,VD,canton,all,agegroup_food,all,1040.0,855106.0,121.62,NaN,952.7,NaN,12.0,NaN,NaN,NaN,NaN,True
716,cases,2025,year,VS,canton,all,agegroup_food,all,507.0,371288.0,136.55,NaN,462.0,NaN,5.8,NaN,NaN,NaN,NaN,True
717,cases,2025,year,ZG,canton,all,agegroup_food,all,116.0,133739.0,86.74,NaN,107.3,NaN,1.3,NaN,NaN,NaN,NaN,True
718,cases,2025,year,ZH,canton,all,agegroup_food,all,1379.0,1620020.0,85.12,NaN,1187.3,NaN,15.9,NaN,NaN,NaN,NaN,True

In [ ]:
data_cantons_100 = data_cantons.copy()

# Wert pro 100000 einfügen
data_cantons_100["value_100000"] = data_cantons_100["value"] / data_cantons_100["pop"] * 100000

data_cantons_100["value_100000"] = data_cantons_100["value_100000"].round(1)

data_cantons_100

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,...,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete,value_100000
332,cases,2013,year,AG,canton,all,agegroup_food,all,546.0,636362.0,...,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True,85.8
333,cases,2013,year,AI,canton,all,agegroup_food,all,25.0,15778.0,...,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,True,158.4
334,cases,2013,year,AR,canton,all,agegroup_food,all,52.0,53691.0,...,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True,96.9
335,cases,2013,year,BE,canton,all,agegroup_food,all,958.0,1001281.0,...,NaN,NaN,NaN,12.8,NaN,NaN,NaN,NaN,True,95.7
336,cases,2013,year,BL,canton,all,agegroup_food,all,417.0,278656.0,...,NaN,NaN,NaN,5.6,NaN,NaN,NaN,NaN,True,149.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,cases,2025,year,UR,canton,all,agegroup_food,all,20.0,38275.0,...,NaN,23.3,NaN,0.2,NaN,NaN,NaN,NaN,True,52.3
715,cases,2025,year,VD,canton,all,agegroup_food,all,1040.0,855106.0,...,NaN,952.7,NaN,12.0,NaN,NaN,NaN,NaN,True,121.6
716,cases,2025,year,VS,canton,all,agegroup_food,all,507.0,371288.0,...,NaN,462.0,NaN,5.8,NaN,NaN,NaN,NaN,True,136.6
717,cases,2025,year,ZG,canton,all,agegroup_food,all,116.0,133739.0,...,NaN,107.3,NaN,1.3,NaN,NaN,NaN,NaN,True,86.7
718,cases,2025,year,ZH,canton,all,agegroup_food,all,1379.0,1620020.0,...,NaN,1187.3,NaN,15.9,NaN,NaN,NaN,NaN,True,85.1

In [ ]:
# nur 2025
data_cantons_100_2025 = data_cantons_100[data_cantons_100["temporal"] == "2025"]

#Bar Chart
bar_georegion = alt.Chart(data_cantons_100_2025).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("value_100000", title="Mean Cases")
).properties(
    title="Campylobacteriosis Georegion 2025 pro 100000"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value_100000:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)