# Share 5 - BAG
## Shigellose
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/shigellosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/shigellosis/data

Werden monatlich geupdatet

Obligatorische Meldung

In [1]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [2]:
# Daten laden --> read_csv / read_excel
# Falls mehrere sheets --> sheet_name="sheet"


data = pd.read_csv("data/shigellosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Variablen

In [3]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'value', 'pop',
       'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

* valueCategory: Was gemessen wird --> Hier: Anzahl gemeldete Fälle
* temporal: Welcher Zeitabschnitt --> Jahr und Monat
* temporal_type: Typ der Zeit --> Monat
* georegion: Kanton oder Land --> hier Anfang Land später Kanton
* georegion_type: Typ der Georegion --> Land/Kantonal
* agegroup: Alterskategorie
* agegroup_type: Zuordnung zur Oberthema --> bei allen gleich
* sex: Geschlecht
* value: Wert basierend auf vorhergehende Kategorien
* pop: Bevölkerung zum Zeitpunkt der Erhebung
* incValue: neuaufgetrettene Fälle innerhalb der Gruppe und Zeit
* valueYearCumSum: Gesamter Wert über das Jahr
* valueMean3y: Durchschnittswert der letzten drei Jahre
* trend: ist der Trend abnehmend(falling), gleich(stagnant) oder steigend(rising)
* prct: prozentualer Anteil der Fälle in den Kategorien und Zeiteinheit
* deltaValue: Unterschied des value zum vorherigen Wert
* deltaIncValue: Unterschied des incValue zum vorherigen Wert
* incValuePrctChange: Prozentualer Unterschied zum vorherigen Wert
* valueMean5y: Durchschnittlicher Wert der letzten 5 Jahre
* dataComplete: ist dieser Datenpunkt komplett

In [4]:
data.dtypes

valueCategory          object
temporal               object
temporal_type          object
georegion              object
georegion_type         object
agegroup               object
agegroup_type          object
sex                    object
value                 float64
pop                   float64
incValue              float64
valueYearCumSum       float64
valueMean3y           float64
trend                  object
prct                  float64
deltaValue            float64
deltaIncValue         float64
incValuePrctChange    float64
valueMean5y           float64
dataComplete             bool
dtype: object

### Datensatz für Cases

--> Die Durchschnittswerte sind als Einzelne Datenpunkte erhoben

In [5]:
data_def = data[data["valueCategory"] == "cases"]

data_def

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,cases,2025,year,UR,canton,all,agegroup_food,all,0.0,38275.0,0.00,NaN,0.3,NaN,0.0,NaN,NaN,NaN,NaN,True
705,cases,2025,year,VD,canton,all,agegroup_food,all,37.0,855106.0,4.33,NaN,34.0,NaN,15.9,NaN,NaN,NaN,NaN,True
706,cases,2025,year,VS,canton,all,agegroup_food,all,10.0,371288.0,2.69,NaN,7.3,NaN,4.3,NaN,NaN,NaN,NaN,True
707,cases,2025,year,ZG,canton,all,agegroup_food,all,4.0,133739.0,2.99,NaN,4.7,NaN,1.7,NaN,NaN,NaN,NaN,True
708,cases,2025,year,ZH,canton,all,agegroup_food,all,37.0,1620020.0,2.28,NaN,37.0,NaN,15.9,NaN,NaN,NaN,NaN,True

### Datensatz für Agegroup

In [6]:
data_med = data[data["valueCategory"] == "cases_10y_mean"]

data_med

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
709,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
710,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
711,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,2.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
712,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,1.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
713,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
714,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
715,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
716,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
717,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,2.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
718,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,1.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
719,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
720,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
721,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
722,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
723,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,3.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
724,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,2.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
725,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
726,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
727,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
728,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
729,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,3.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
730,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,1.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
731,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
732,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

### Datensatz für Geschlecht

In [ ]:
data_sex = data[data["valueCategory"] == "cases_10y_cumsum"]

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
814,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,all,7169.0,...,NaN,NaN,NaN,NaN,48.4,NaN,NaN,NaN,NaN,True
815,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,all,7628.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
816,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,all,15.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
817,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,all,7444.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
818,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,all,7906.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
819,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,all,14.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
820,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,all,7985.0,...,NaN,NaN,NaN,NaN,48.7,NaN,NaN,NaN,NaN,True
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Visuelle Analyse

In [7]:
#Gruppieren nach georegion und Werte summieren
counts = (
    data_def.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Shigellosis Georegion"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

* Teilweise CH, teilweise CHFL

In [8]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="Shigellosis Georegion 2013-2025"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

In [9]:
#Gruppieren nach georegion und Werte summieren
counts = (
    data_def.groupby("temporal")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_temporal = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("sum_value", title="Cases")
).properties(
    title="Shigellosis Temporal"
)

# Textlabels
text = bar_temporal.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_temporal = bar_temporal + text
bar_temporal

alt.LayerChart(...)

* Datensatz aufteilen in monatlich und Jährlich

In [10]:
data_1 = data_def.copy()

data_year = data_1[data_1["temporal_type"] == "year"]

data_year

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,11.0,636362.0,1.73,NaN,NaN,NaN,7.5,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,0.0,15778.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,0.0,53691.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,9.0,1001281.0,0.90,NaN,NaN,NaN,6.1,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,7.0,278656.0,2.51,NaN,NaN,NaN,4.8,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,cases,2025,year,UR,canton,all,agegroup_food,all,0.0,38275.0,0.00,NaN,0.3,NaN,0.0,NaN,NaN,NaN,NaN,True
705,cases,2025,year,VD,canton,all,agegroup_food,all,37.0,855106.0,4.33,NaN,34.0,NaN,15.9,NaN,NaN,NaN,NaN,True
706,cases,2025,year,VS,canton,all,agegroup_food,all,10.0,371288.0,2.69,NaN,7.3,NaN,4.3,NaN,NaN,NaN,NaN,True
707,cases,2025,year,ZG,canton,all,agegroup_food,all,4.0,133739.0,2.99,NaN,4.7,NaN,1.7,NaN,NaN,NaN,NaN,True
708,cases,2025,year,ZH,canton,all,agegroup_food,all,37.0,1620020.0,2.28,NaN,37.0,NaN,15.9,NaN,NaN,NaN,NaN,True

In [11]:
# Ohne Kantone
data_year_CH = data_year[data_year["georegion"].isin(["CH", "CHFL"])]

bar_year = alt.Chart(data_year_CH).mark_bar().encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("incValue")
).properties(
    title="Shigellosis Year"
)

bar_year

alt.Chart(...)

* Peak in 2018
* Meklich weniger Fälle in 2020
* Erneuter Anstieg am 2022

In [12]:
data_2 = data_def.copy()

data_month = data_2[data_2["temporal_type"] == "month"]

data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,17.0,9091674.0,0.19,70.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,18.0,9091674.0,0.20,88.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,23.0,9091674.0,0.25,111.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,23.0,9091674.0,0.25,134.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,27.0,9091674.0,0.30,161.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True

In [13]:
bar_month = alt.Chart(data_month).mark_bar().encode(
    x=alt.X("temporal:N", title="Temporal"),
    y=alt.Y("value:Q", title="Cases"),
    color=alt.Color("trend:N")
).properties(
    title="Shigellosis Month"
)

bar_month

alt.Chart(...)

* sehr unterschiedlich im Jahr
* merklich weniger Fälle 2020

In [14]:
bar_age = alt.Chart(data_med).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Salmonellosis Altersgruppen 2022 - 2025"
)

bar_age

alt.Chart(...)

In [16]:
data_age_2025 = data_med[data_med["temporal"] == "2025"]

bar_age_2 = alt.Chart(data_age_2025).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases")
).properties(
    title="Salmonellosis Altersgruppen 2025"
)

bar_age_2

alt.Chart(...)