# Share 5 - BAG
## EHEC - Enterohämorrhagische Escherichia coli-Infektion
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/ehec/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/ehec/data

Werden monatlich geupdatet

Oblig. Meldung

In [1]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [2]:
# Daten laden --> read_csv / read_excel
# Falls mehrere sheets --> sheet_name="sheet"


data = pd.read_csv("data/ehec/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Variablen

In [3]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

* valueCategory: Was gemessen wird --> Hier: Anzahl gemeldete Fälle
* temporal: Welcher Zeitabschnitt --> Jahr und Monat
* temporal_type: Typ der Zeit --> Monat
* georegion: Kanton oder Land --> hier Anfang Land später Kanton
* georegion_type: Typ der Georegion --> Land/Kantonal
* agegroup: Alterskategorie
* agegroup_type: Zuordnung zur Oberthema --> bei allen gleich
* sex: Geschlecht
* value: Wert basierend auf vorhergehende Kategorien
* pop: Bevölkerung zum Zeitpunkt der Erhebung
* incValue: neuaufgetrettene Fälle innerhalb der Gruppe und Zeit
* valueYearCumSum: Gesamter Wert über das Jahr
* valueMean3y: Durchschnittswert der letzten drei Jahre
* trend: ist der Trend abnehmend(falling), gleich(stagnant) oder steigend(rising)
* prct: prozentualer Anteil der Fälle in den Kategorien und Zeiteinheit
* deltaValue: Unterschied des value zum vorherigen Wert
* deltaIncValue: Unterschied des incValue zum vorherigen Wert
* incValuePrctChange: Prozentualer Unterschied zum vorherigen Wert
* valueMean5y: Durchschnittlicher Wert der letzten 5 Jahre
* dataComplete: ist dieser Datenpunkt komplett

In [4]:
data.dtypes

valueCategory          object
temporal               object
temporal_type          object
georegion              object
georegion_type         object
agegroup               object
agegroup_type          object
sex                    object
type                   object
value                 float64
pop                   float64
incValue              float64
valueYearCumSum       float64
valueMean3y           float64
trend                  object
prct                  float64
deltaValue            float64
deltaIncValue         float64
incValuePrctChange    float64
valueMean5y           float64
dataComplete             bool
dtype: object

### Datensatz für Cases

--> Die Durchschnittswerte sind als Einzelne Datenpunkte erhoben

In [5]:
data_def = data[data["valueCategory"] == "cases"]

data_def

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,cases,2023,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1217.0,...,13.52,NaN,1105.3,NaN,98.2,NaN,NaN,NaN,NaN,True
731,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,hus,24.0,...,0.26,NaN,23.3,NaN,1.7,NaN,NaN,NaN,NaN,True
732,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1368.0,...,15.05,NaN,1255.3,NaN,98.3,NaN,NaN,NaN,NaN,True
733,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,hus,23.0,...,0.25,NaN,23.0,NaN,1.6,NaN,NaN,NaN,NaN,True
734,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1423.0,...,15.65,NaN,1336.0,NaN,98.4,NaN,NaN,NaN,NaN,True

### Datensatz für Durchschnittswerte & Agegroup

In [6]:
data_med = data[data["valueCategory"] == "cases_10y_mean"]

data_med

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
735,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,9.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
736,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,6.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
737,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,5.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
738,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,5.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
739,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,11.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
740,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
741,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,10.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
742,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,7.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
743,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,6.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
744,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,6.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
745,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,13.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
746,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
747,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,12.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
748,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,8.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
749,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,7.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
750,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,7.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
751,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,15.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
752,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
753,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,13.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
754,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,10.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
755,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,8.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
756,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,8.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
757,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,17.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
758,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

### Datensatz für Geschlecht

In [ ]:
data_sex = data[data["valueCategory"] == "cases_10y_cumsum"]

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
814,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,all,7169.0,...,NaN,NaN,NaN,NaN,48.4,NaN,NaN,NaN,NaN,True
815,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,all,7628.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
816,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,all,15.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
817,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,all,7444.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
818,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,all,7906.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
819,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,all,14.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
820,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,all,7985.0,...,NaN,NaN,NaN,NaN,48.7,NaN,NaN,NaN,NaN,True
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Visuelle Analyse

In [7]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="EHEC Georegion 2013-2025"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

In [8]:


#Gruppieren nach georegion und Werte summieren
counts = (
    data_def.groupby("temporal")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_temporal = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("sum_value", title="Cases")
).properties(
    title="EHEC Temporal"
)

# Textlabels
text = bar_temporal.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_temporal = bar_temporal + text
bar_temporal

alt.LayerChart(...)

* Datensatz aufteilen in monatlich und Jährlich

In [9]:
data_1 = data_def.copy()

data_year = data_1[data_1["temporal_type"] == "year"]

data_year

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,9.0,...,1.41,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,13.0,...,1.30,NaN,NaN,NaN,15.9,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,6.0,...,2.15,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,cases,2023,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1217.0,...,13.52,NaN,1105.3,NaN,98.2,NaN,NaN,NaN,NaN,True
731,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,hus,24.0,...,0.26,NaN,23.3,NaN,1.7,NaN,NaN,NaN,NaN,True
732,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1368.0,...,15.05,NaN,1255.3,NaN,98.3,NaN,NaN,NaN,NaN,True
733,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,hus,23.0,...,0.25,NaN,23.0,NaN,1.6,NaN,NaN,NaN,NaN,True
734,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1423.0,...,15.65,NaN,1336.0,NaN,98.4,NaN,NaN,NaN,NaN,True

In [10]:
# Ohne Kantone
data_year_CH = data_year[data_year["georegion"].isin(["CH", "CHFL"])]

bar_year = alt.Chart(data_year_CH).mark_bar().encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("incValue")
).properties(
    title="EHEC Year"
)

bar_year

alt.Chart(...)

In [11]:
data_2 = data_def.copy()

data_month = data_2[data_2["temporal_type"] == "month"]

data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,112.0,...,1.23,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,138.0,...,1.52,544.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,165.0,...,1.81,709.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,267.0,...,2.94,976.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,261.0,...,2.87,1237.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True

In [12]:
bar_month = alt.Chart(data_month).mark_bar().encode(
    x=alt.X("temporal:N", title="Temporal"),
    y=alt.Y("value:Q", title="Cases"),
    color=alt.Color("trend:N")
).properties(
    title="EHEC Month"
)

bar_month

alt.Chart(...)

In [15]:
bar_age = alt.Chart(data_med).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="Salmonellosis Altersgruppen 2022 - 2025"
)

bar_age

alt.Chart(...)

In [17]:
data_age_2025 = data_med[data_med["temporal"] == "2025"]

bar_age_2 = alt.Chart(data_age_2025).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases")
).properties(
    title="Salmonellosis Altersgruppen 2025"
)

bar_age_2

alt.Chart(...)