# Share 5 - BAG
## EHEC - Enterohämorrhagische Escherichia coli-Infektion
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/ehec/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/ehec/data

Werden monatlich geupdatet

Oblig. Meldung

In [95]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [96]:
# Daten laden --> read_csv / read_excel
# Falls mehrere sheets --> sheet_name="sheet"


data = pd.read_csv("data/ehec/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

### Variablen

In [97]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

* valueCategory: Was gemessen wird --> Hier: Anzahl gemeldete Fälle
* temporal: Welcher Zeitabschnitt --> Jahr und Monat
* temporal_type: Typ der Zeit --> Monat
* georegion: Kanton oder Land --> hier Anfang Land später Kanton
* georegion_type: Typ der Georegion --> Land/Kantonal
* agegroup: Alterskategorie
* agegroup_type: Zuordnung zur Oberthema --> bei allen gleich
* sex: Geschlecht
* value: Wert basierend auf vorhergehende Kategorien
* pop: Bevölkerung zum Zeitpunkt der Erhebung
* incValue: neuaufgetrettene Fälle innerhalb der Gruppe und Zeit
* valueYearCumSum: Gesamter Wert über das Jahr
* valueMean3y: Durchschnittswert der letzten drei Jahre
* trend: ist der Trend abnehmend(falling), gleich(stagnant) oder steigend(rising)
* prct: prozentualer Anteil der Fälle in den Kategorien und Zeiteinheit
* deltaValue: Unterschied des value zum vorherigen Wert
* deltaIncValue: Unterschied des incValue zum vorherigen Wert
* incValuePrctChange: Prozentualer Unterschied zum vorherigen Wert
* valueMean5y: Durchschnittlicher Wert der letzten 5 Jahre
* dataComplete: ist dieser Datenpunkt komplett

In [98]:
data.dtypes

valueCategory          object
temporal               object
temporal_type          object
georegion              object
georegion_type         object
agegroup               object
agegroup_type          object
sex                    object
type                   object
value                 float64
pop                   float64
incValue              float64
valueYearCumSum       float64
valueMean3y           float64
trend                  object
prct                  float64
deltaValue            float64
deltaIncValue         float64
incValuePrctChange    float64
valueMean5y           float64
dataComplete             bool
dtype: object

### Datensatz für Cases

--> Die Durchschnittswerte sind als Einzelne Datenpunkte erhoben

In [99]:
data_def = data[data["valueCategory"] == "cases"]

data_def

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,cases,2023,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1217.0,...,13.52,NaN,1105.3,NaN,98.2,NaN,NaN,NaN,NaN,True
731,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,hus,24.0,...,0.26,NaN,23.3,NaN,1.7,NaN,NaN,NaN,NaN,True
732,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1368.0,...,15.05,NaN,1255.3,NaN,98.3,NaN,NaN,NaN,NaN,True
733,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,hus,23.0,...,0.25,NaN,23.0,NaN,1.6,NaN,NaN,NaN,NaN,True
734,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1423.0,...,15.65,NaN,1336.0,NaN,98.4,NaN,NaN,NaN,NaN,True

### Datensatz für Agegroup

In [100]:
data_med = data[data["valueCategory"] == "cases_10y_mean"]

data_med

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
735,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,9.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
736,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,6.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
737,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,5.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
738,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,5.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
739,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,11.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
740,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
741,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,10.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
742,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,7.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
743,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,6.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
744,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,6.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
745,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,13.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
746,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
747,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,12.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
748,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,8.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
749,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,7.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
750,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,7.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
751,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,15.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
752,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
753,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,13.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
754,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,10.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
755,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,8.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
756,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,8.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
757,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,17.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
758,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [101]:
# Exportieren des Datensatzes für Fälle pro Altersklasse
# data_med.to_csv("./export/data_ehec_fälle_altersklasse.csv", index=False)

### Datensatz für Geschlecht

In [102]:
data_sex = data[data["valueCategory"] == "cases_10y_cumsum"]

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
759,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,all,3600.0,...,NaN,NaN,NaN,NaN,55.8,NaN,NaN,NaN,NaN,True
760,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,all,2843.0,...,NaN,NaN,NaN,NaN,44.1,NaN,NaN,NaN,NaN,True
761,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,all,3.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
762,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,all,4228.0,...,NaN,NaN,NaN,NaN,55.6,NaN,NaN,NaN,NaN,True
763,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,all,3369.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
764,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,all,5.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
765,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,all,4931.0,...,NaN,NaN,NaN,NaN,55.6,NaN,NaN,NaN,NaN,True
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [103]:
# Exportieren des Datensatzes für Fälle Geschlechterverteilung
data_sex.to_csv("./export/data_ehec_fälle_geschlecht.csv", index=False)

### Visuelle Analyse

In [104]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="EHEC Georegion 2013-2025"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

* ZH am höchsten --> grösster Kanton
* kleine Kantone --> weniger Fälle

In [105]:
# nur 2025
data_cantons_2025 = data_cantons[data_cantons["temporal"] == "2025"]

#Gruppieren nach georegion und Werte summieren
counts = (
    data_cantons_2025.groupby("georegion")
        .agg(sum_value=("value", "sum"))
        .reset_index()
)

#Bar Chart
bar_georegion_2025 = alt.Chart(counts).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("sum_value", title="Total Cases")
).properties(
    title="EHEC Georegion 2025"
)

# Textlabels
text = bar_georegion_2025.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="sum_value:Q"
)

# Kombinieren
bar_georegion_2025 = bar_georegion_2025 + text
bar_georegion_2025

alt.LayerChart(...)

In [106]:
data_1 = data_def.copy()

data_year = data_1[data_1["temporal_type"] == "year"]

data_year

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,9.0,...,1.41,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,13.0,...,1.30,NaN,NaN,NaN,15.9,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,6.0,...,2.15,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
730,cases,2023,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1217.0,...,13.52,NaN,1105.3,NaN,98.2,NaN,NaN,NaN,NaN,True
731,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,hus,24.0,...,0.26,NaN,23.3,NaN,1.7,NaN,NaN,NaN,NaN,True
732,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1368.0,...,15.05,NaN,1255.3,NaN,98.3,NaN,NaN,NaN,NaN,True
733,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,hus,23.0,...,0.25,NaN,23.0,NaN,1.6,NaN,NaN,NaN,NaN,True
734,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1423.0,...,15.65,NaN,1336.0,NaN,98.4,NaN,NaN,NaN,NaN,True

In [107]:
# Exportieren des Datensatzes für Fälle pro Kanton
# data_year.to_csv("./export/data_ehec_fälle_georegion.csv", index=False)

In [108]:
# Ohne Kantone
data_year_CH = data_year[data_year["georegion"].isin(["CH"])]

bar_year = alt.Chart(data_year_CH).mark_bar().encode(
    x=alt.X("temporal", title="Temporal"),
    y=alt.Y("value", title="Cases")
).properties(
    title="EHEC Year"
)

# Textlabels
text = bar_year.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_year = bar_year + text
bar_year

alt.LayerChart(...)

* Steigende Fallzahlen in den letzten Jahren

In [109]:
data_2 = data_def.copy()

data_month = data_2[data_2["temporal_type"] == "month"]

data_month

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,112.0,...,1.23,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,138.0,...,1.52,544.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,165.0,...,1.81,709.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,267.0,...,2.94,976.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,261.0,...,2.87,1237.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True

In [110]:
# Exportieren des Datensatzes für Fälle pro Monat
# data_month.to_csv("./export/data_ehec_fälle_monat.csv", index=False)

In [111]:
#Gruppieren nach Jahren und Werte summieren


bar_month = alt.Chart(data_month).mark_bar().encode(
    x=alt.X("temporal:N", title="Temporal"),
    y=alt.Y("value:Q", title="Cases"),
    color=alt.Color("trend:N")
).properties(
    title="EHEC Month"
)

# Textlabels
text = bar_month.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_month = bar_month + text
bar_month

alt.LayerChart(...)

* im Sommer am Höchsten¨
* im Winter tiefer
* steigende Zahlen in den letzten Jahren

In [112]:
bar_age = alt.Chart(data_med).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="EHEC Altersgruppen 2022 - 2025"
)

bar_age

alt.Chart(...)

In [113]:
data_age_2025 = data_med[data_med["temporal"] == "2025"]

bar_age_2 = alt.Chart(data_age_2025).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("incValue", title="Cases")
).properties(
    title="EHEC Altersgruppen 2025"
)

# Textlabels
text = bar_age_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="incValue:Q"
)

bar_age_2 = bar_age_2 + text

bar_age_2

alt.LayerChart(...)

In [114]:
bar_sex = alt.Chart(data_sex).mark_bar().encode(
    x=alt.X("sex", title="Sex"),
    y=alt.Y("value", title="Cases"),
    color=alt.Color("temporal")
).properties(
    title="EHEC Geschlechterverteilung 2022 - 2025"
)

bar_sex

alt.Chart(...)

In [115]:
data_sex_2025 = data_sex[data_sex["temporal"] == "2025"]

bar_sex_2 = alt.Chart(data_sex_2025).mark_bar().encode(
    x=alt.X("sex", title="Geschlecht"),
    y=alt.Y("value", title="Cases")
).properties(
    title="EHEC Geschlechterverteilung 2025"
)

# Textlabels
text = bar_sex_2.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value:Q"
)

bar_sex_2 = bar_sex_2 + text
bar_sex_2

alt.LayerChart(...)

### Durchschnittsberechnungen & -visualisierungen

In [116]:
# Ohne Kantone --> ~
data_cantons = data_def[~data_def["georegion"].isin(["CH", "CHFL"])]

#Gruppieren nach georegion und Werte summieren
counts_mean = (
    data_cantons.groupby("georegion")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

#Bar Chart
bar_georegion = alt.Chart(counts_mean).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("mean_value", title="Mean Cases")
).properties(
    title="EHEC Georegion 2013-2025 Mean"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)

In [117]:
# Jahr und Monat trennen
data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)

data_month

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_27603/2880901401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_27603/2880901401.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_month[["year", "month"]] = data_def["temporal"].str.split("-", expand=True)

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete,year,month
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M01
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M02
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,2013,M03
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2013,M04
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True,2013,M05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,112.0,...,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True,2026,M04
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,138.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M05
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,165.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M06
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,267.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M07
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,261.0,...,NaN,rising,NaN,NaN,NaN,NaN,NaN,True,2026,M08

In [118]:
counts_mean = (
    data_month.groupby("month")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

bar_month = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("month:N", title="Month"),
    y=alt.Y("mean_value:Q", title="Cases")
).properties(
    title="EHEC Month 2013-2026 Mean"
)

# Textlabels
text = bar_month.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_month = bar_month + text
bar_month

alt.LayerChart(...)

In [119]:
counts_mean = (
    data_med.groupby("agegroup")
        .agg(mean_value=("incValue", "mean")).round(0)
        .reset_index()
)

bar_age = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("agegroup", title="Agegroup"),
    y=alt.Y("mean_value", title="Cases")
).properties(
    title="EHEC Altersgruppen 2022 - 2025 Mean IncValue"
)

# Textlabels
text = bar_age.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_age = bar_age + text
bar_age

alt.LayerChart(...)

In [120]:
counts_mean = (
    data_sex.groupby("sex")
        .agg(mean_value=("value", "mean")).round(0)
        .reset_index()
)

bar_sex = alt.Chart(counts_mean).mark_bar().encode(
    x=alt.X("sex", title="Sex"),
    y=alt.Y("mean_value", title="Cases")
).properties(
    title="EHEC Geschlechterverteilung 2022 - 2025 Mean"
)

# Textlabels
text = bar_sex.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="mean_value:Q"
)

bar_sex = bar_sex + text
bar_sex

bar_sex

alt.LayerChart(...)

### Auf 100'000 Personen gerechnet

In [121]:
data_cantons

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,9.0,...,1.41,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,13.0,...,1.30,NaN,NaN,NaN,15.9,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,6.0,...,2.15,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,cases,2025,year,UR,canton,all,agegroup_food,all,all,6.0,...,15.68,NaN,7.0,NaN,0.4,NaN,NaN,NaN,NaN,True
705,cases,2025,year,VD,canton,all,agegroup_food,all,all,196.0,...,22.92,NaN,179.0,NaN,13.6,NaN,NaN,NaN,NaN,True
706,cases,2025,year,VS,canton,all,agegroup_food,all,all,81.0,...,21.82,NaN,59.7,NaN,5.6,NaN,NaN,NaN,NaN,True
707,cases,2025,year,ZG,canton,all,agegroup_food,all,all,23.0,...,17.20,NaN,22.7,NaN,1.6,NaN,NaN,NaN,NaN,True
708,cases,2025,year,ZH,canton,all,agegroup_food,all,all,240.0,...,14.81,NaN,215.7,NaN,16.7,NaN,NaN,NaN,NaN,True

In [122]:
data_cantons_100 = data_cantons.copy()

# Wert pro 100000 einfügen
data_cantons_100["value_100000"] = data_cantons_100["value"] / data_cantons_100["pop"] * 100000

data_cantons_100["value_100000"] = data_cantons_100["value_100000"].round(1)

data_cantons_100

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete,value_100000
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,9.0,...,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,True,1.4
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True,0.0
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True,0.0
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,13.0,...,NaN,NaN,NaN,15.9,NaN,NaN,NaN,NaN,True,1.3
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,6.0,...,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True,2.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,cases,2025,year,UR,canton,all,agegroup_food,all,all,6.0,...,NaN,7.0,NaN,0.4,NaN,NaN,NaN,NaN,True,15.7
705,cases,2025,year,VD,canton,all,agegroup_food,all,all,196.0,...,NaN,179.0,NaN,13.6,NaN,NaN,NaN,NaN,True,22.9
706,cases,2025,year,VS,canton,all,agegroup_food,all,all,81.0,...,NaN,59.7,NaN,5.6,NaN,NaN,NaN,NaN,True,21.8
707,cases,2025,year,ZG,canton,all,agegroup_food,all,all,23.0,...,NaN,22.7,NaN,1.6,NaN,NaN,NaN,NaN,True,17.2
708,cases,2025,year,ZH,canton,all,agegroup_food,all,all,240.0,...,NaN,215.7,NaN,16.7,NaN,NaN,NaN,NaN,True,14.8

In [123]:
# nur 2025
data_cantons_100_2025 = data_cantons_100[data_cantons_100["temporal"] == "2025"]

#Bar Chart
bar_georegion = alt.Chart(data_cantons_100_2025).mark_bar(color="aqua").encode(
    x=alt.X("georegion", title="Georegion"),
    y=alt.Y("value_100000", title="Mean Cases")
).properties(
    title="EHEC Georegion 2025 pro 100000"
)

# Textlabels
text = bar_georegion.mark_text(
    align="center",
    dy=-5,
    size=10
).encode(
    text="value_100000:Q"
)

# Kombinieren
bar_georegion = bar_georegion + text
bar_georegion

alt.LayerChart(...)