# Share 5 -BAG
## Salmonellosis - Datensatz reduziert
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/data

--> Mission: Einen Datensatz pro Visualisierung erstellen

In [128]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [129]:
data = pd.read_csv("data/salmonellosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [130]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

## Reduktion des Datensatzes
### Altersverteilung
Variablen:
* valueCategory
* temporal
* agegroup != "all"
* agegroup_type
* incValue
* incValue gerundet

In [131]:
data_age = data.copy()
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [132]:
# Nur Zeilen in denen Agegroup nicht "all" ist

data_age = data_age[data_age["agegroup"] != "all"]
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
790,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,31.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
791,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
792,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,12.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
793,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
794,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,17.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
795,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
796,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,31.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
797,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
798,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,12.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
799,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
800,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,18.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
801,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
802,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,33.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
803,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,23.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
804,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,13.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
805,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
806,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,19.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
807,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
808,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,35.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
809,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,24.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
810,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,14.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
811,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,13.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
812,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
813,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [133]:
# Auswahl der Variablen
col_selection_age = ["valueCategory", "temporal", "agegroup", "agegroup_type", "incValue"]

col_selection_age

['valueCategory', 'temporal', 'agegroup', 'agegroup_type', 'incValue']

In [134]:
data_age = data_age[col_selection_age]

data_age

      valueCategory temporal agegroup  agegroup_type  incValue
790  cases_10y_mean     2022   0 - 16  agegroup_food     31.12
791  cases_10y_mean     2022  17 - 24  agegroup_food     22.53
792  cases_10y_mean     2022  25 - 44  agegroup_food     12.21
793  cases_10y_mean     2022  45 - 64  agegroup_food     12.02
794  cases_10y_mean     2022      65+  agegroup_food     17.73
795  cases_10y_mean     2022  unknown  agegroup_food       NaN
796  cases_10y_mean     2023   0 - 16  agegroup_food     31.94
797  cases_10y_mean     2023  17 - 24  agegroup_food     22.53
798  cases_10y_mean     2023  25 - 44  agegroup_food     12.63
799  cases_10y_mean     2023  45 - 64  agegroup_food     12.21
800  cases_10y_mean     2023      65+  agegroup_food     18.62
801  cases_10y_mean     2023  unknown  agegroup_food       NaN
802  cases_10y_mean     2024   0 - 16  agegroup_food     33.58
803  cases_10y_mean     2024  17 - 24  agegroup_food     23.61
804  cases_10y_mean     2024  25 - 44  agegroup_food     13.55
805  cases_10y_mean     2024  45 - 64  agegroup_food     12.78
806  cases_10y_mean     2024      65+  agegroup_food     19.72
807  cases_10y_mean     2024  unknown  agegroup_food       NaN
808  cases_10y_mean     2025   0 - 16  agegroup_food     35.14
809  cases_10y_mean     2025  17 - 24  agegroup_food     24.79
810  cases_10y_mean     2025  25 - 44  agegroup_food     14.36
811  cases_10y_mean     2025  45 - 64  agegroup_food     13.10
812  cases_10y_mean     2025      65+  agegroup_food     20.88
813  cases_10y_mean     2025  unknown  agegroup_food       NaN

In [135]:
data_age.insert(
    data_age.columns.get_loc("incValue") + 1,
    "incValue_rounded",
    data_age["incValue"].round(0)
)

data_age

,valueCategory,temporal,agegroup,agegroup_type,incValue,incValue_rounded
790,cases_10y_mean,2022,0 - 16,agegroup_food,31.12,31.0
791,cases_10y_mean,2022,17 - 24,agegroup_food,22.53,23.0
792,cases_10y_mean,2022,25 - 44,agegroup_food,12.21,12.0
793,cases_10y_mean,2022,45 - 64,agegroup_food,12.02,12.0
794,cases_10y_mean,2022,65+,agegroup_food,17.73,18.0
795,cases_10y_mean,2022,unknown,agegroup_food,NaN,NaN
796,cases_10y_mean,2023,0 - 16,agegroup_food,31.94,32.0
797,cases_10y_mean,2023,17 - 24,agegroup_food,22.53,23.0
798,cases_10y_mean,2023,25 - 44,agegroup_food,12.63,13.0
799,cases_10y_mean,2023,45 - 64,agegroup_food,12.21,12.0
800,cases_10y_mean,2023,65+,agegroup_food,18.62,19.0
801,cases_10y_mean,2023,unknown,agegroup_food,NaN,NaN
802,cases_10y_mean,2024,0 - 16,agegroup_food,33.58,34.0
803,cases_10y_mean,2024,17 - 24,agegroup_food,23.61,24.0
804,cases_10y_mean,2024,25 - 44,agegroup_food,13.55,14.0
805,cases_10y_mean,2024,45 - 64,agegroup_food,12.78,13.0
806,cases_10y_mean,2024,65+,agegroup_food,19.72,20.0
807,cases_10y_mean,2024,unknown,agegroup_food,NaN,NaN
808,cases_10y_mean,2025,0 - 16,agegroup_food,35.14,35.0
809,cases_10y_mean,2025,17 - 24,agegroup_food,24.79,25.0
810,cases_10y_mean,2025,25 - 44,agegroup_food,14.36,14.0
811,cases_10y_mean,2025,45 - 64,agegroup_food,13.10,13.0
812,cases_10y_mean,2025,65+,agegroup_food,20.88,21.0
813,cases_10y_mean,2025,unknown,agegroup_food,NaN,NaN

In [136]:
# Exportieren des Datensatzes
# data_age.to_csv("./export/reduziert_für_viz/data_salmonellosis_age.csv", index=False)

### Georegion
Variablen:
* valueCategory
* temporal
* georegion
* georegion_type = "canton"
* (value)
* incValue 
* incValue gerundet
* kategorisierter incValue (12 Stufen)

In [137]:
data_geo = data.copy()
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [138]:
# Nur Zeilen in georegion_type = "canton"

data_geo = data_geo[data_geo["georegion_type"] == "canton"]
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,86.0,...,13.51,NaN,NaN,NaN,6.8,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,11.0,...,20.49,NaN,NaN,NaN,0.9,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,141.0,...,14.08,NaN,NaN,NaN,11.1,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,47.0,...,16.87,NaN,NaN,NaN,3.7,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,cases,2025,year,UR,canton,all,agegroup_food,all,all,12.0,...,31.35,NaN,9.0,NaN,0.5,NaN,NaN,NaN,NaN,True
708,cases,2025,year,VD,canton,all,agegroup_food,all,all,309.0,...,36.14,NaN,278.7,NaN,13.6,NaN,NaN,NaN,NaN,True
709,cases,2025,year,VS,canton,all,agegroup_food,all,all,103.0,...,27.74,NaN,89.0,NaN,4.5,NaN,NaN,NaN,NaN,True
710,cases,2025,year,ZG,canton,all,agegroup_food,all,all,21.0,...,15.70,NaN,24.0,NaN,0.9,NaN,NaN,NaN,NaN,True
711,cases,2025,year,ZH,canton,all,agegroup_food,all,all,341.0,...,21.05,NaN,349.3,NaN,15.0,NaN,NaN,NaN,NaN,True

In [139]:
# Auswahl der Variablen
col_selection_geo = ["valueCategory", "temporal", "georegion", "georegion_type", "incValue"]
col_selection_geo

['valueCategory', 'temporal', 'georegion', 'georegion_type', 'incValue']

In [140]:
data_geo = data_geo[col_selection_geo]
data_geo

    valueCategory temporal georegion georegion_type  incValue
332         cases     2013        AG         canton     13.51
333         cases     2013        AI         canton      0.00
334         cases     2013        AR         canton     20.49
335         cases     2013        BE         canton     14.08
336         cases     2013        BL         canton     16.87
..            ...      ...       ...            ...       ...
707         cases     2025        UR         canton     31.35
708         cases     2025        VD         canton     36.14
709         cases     2025        VS         canton     27.74
710         cases     2025        ZG         canton     15.70
711         cases     2025        ZH         canton     21.05

[341 rows x 5 columns]

In [141]:
# Einfügen des gerundeten incValues

data_geo.insert(
    data_geo.columns.get_loc("incValue")+1,
    "incValue_rounded",
    data_geo["incValue"].round(0)
)

# Vorbereitung für Kategorisierung

bins = 12
labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

data_geo.insert(
    data_geo.columns.get_loc("incValue_rounded")+1,
    "incValue_cat",
    pd.cut(data_geo["incValue"], bins=bins, labels=labels)
)

data_geo

,valueCategory,temporal,georegion,georegion_type,incValue,incValue_rounded,incValue_cat
332,cases,2013,AG,canton,13.51,14.0,4
333,cases,2013,AI,canton,0.00,0.0,1
334,cases,2013,AR,canton,20.49,20.0,5
335,cases,2013,BE,canton,14.08,14.0,4
336,cases,2013,BL,canton,16.87,17.0,4
...,...,...,...,...,...,...,...
707,cases,2025,UR,canton,31.35,31.0,8
708,cases,2025,VD,canton,36.14,36.0,9
709,cases,2025,VS,canton,27.74,28.0,7
710,cases,2025,ZG,canton,15.70,16.0,4
711,cases,2025,ZH,canton,21.05,21.0,5

In [ ]:
# Exportieren des Datensatzes
# data_geo.to_csv("./export/reduziert_für_viz/data_salmonellosis_georegion.csv", index=False)

### Geschlechtlicheverteilung
Variablen:
* valueCategory
* temporal
* sex != "all"
* value
* prct

In [143]:
data_sex = data.copy()

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [145]:
# Nur Datenpunkte zu Geschlecht

data_sex = data_sex[data_sex["sex"] != "all"]
data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
814,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,all,7169.0,...,NaN,NaN,NaN,NaN,48.4,NaN,NaN,NaN,NaN,True
815,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,all,7628.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
816,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,all,15.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
817,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,all,7444.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
818,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,all,7906.0,...,NaN,NaN,NaN,NaN,51.5,NaN,NaN,NaN,NaN,True
819,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,all,14.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
820,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,all,7985.0,...,NaN,NaN,NaN,NaN,48.7,NaN,NaN,NaN,NaN,True
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [146]:
col_selection_sex = ["valueCategory", "temporal", "sex", "value", "prct"]
col_selection_sex

['valueCategory', 'temporal', 'sex', 'value', 'prct']

In [147]:
data_sex = data_sex[col_selection_sex]
data_sex

        valueCategory temporal      sex   value  prct
814  cases_10y_cumsum     2022   female  7169.0  48.4
815  cases_10y_cumsum     2022     male  7628.0  51.5
816  cases_10y_cumsum     2022  unknown    15.0   0.1
817  cases_10y_cumsum     2023   female  7444.0  48.5
818  cases_10y_cumsum     2023     male  7906.0  51.5
819  cases_10y_cumsum     2023  unknown    14.0   0.1
820  cases_10y_cumsum     2024   female  7985.0  48.7
821  cases_10y_cumsum     2024     male  8385.0  51.2
822  cases_10y_cumsum     2024  unknown    17.0   0.1
823  cases_10y_cumsum     2025   female  8402.0  48.5
824  cases_10y_cumsum     2025     male  8899.0  51.4
825  cases_10y_cumsum     2025  unknown    19.0   0.1

In [ ]:
# Exportieren des Datensatzes
# data_sex.to_csv("./export/reduziert_für_viz/data_salmonellosis_sex.csv", index=False)

### Krankheitstypen
Variablen:
* valueCategory
* temporal
* type != "all"
* value
* prct

In [149]:
data_types = data.copy()
data_types

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True