# Share 5 -BAG
## Salmonellosis - Datensatz reduziert
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/salmonellosis/data

--> Mission: Einen Datensatz pro Visualisierung erstellen

In [1]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [2]:
data = pd.read_csv("data/salmonellosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [3]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

## Reduktion des Datensatzes
### Altersverteilung
Variablen:
* valueCategory
* temporal
* agegroup
* agegroup_type
* incValue

In [13]:
data_age = data.copy()
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,87.0,...,1.06,87.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,76.0,...,0.93,163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,63.0,...,0.77,226.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,92.0,...,1.13,318.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,88.0,...,1.08,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,8385.0,...,NaN,NaN,NaN,NaN,51.2,NaN,NaN,NaN,NaN,True
822,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,17.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
823,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,8402.0,...,NaN,NaN,NaN,NaN,48.5,NaN,NaN,NaN,NaN,True
824,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,8899.0,...,NaN,NaN,NaN,NaN,51.4,NaN,NaN,NaN,NaN,True
825,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,19.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [14]:
# Nur Zeilen in denen Agegroup nicht "all" ist

data_age = data_age[data_age["agegroup"] != "all"]
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
790,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,31.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
791,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
792,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,12.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
793,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
794,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,17.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
795,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
796,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,31.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
797,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,22.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
798,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,12.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
799,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
800,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,18.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
801,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
802,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,33.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
803,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,23.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
804,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,13.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
805,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,12.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
806,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,19.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
807,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
808,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,35.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
809,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,24.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
810,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,14.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
811,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,13.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
812,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,20.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
813,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [15]:
# Auswahl der Variablen
col_selection_age = ["valueCategory", "temporal", "agegroup", "agegroup_type", "incValue"]

col_selection_age

['valueCategory', 'temporal', 'agegroup', 'agegroup_type', 'incValue']

In [19]:
data_age = data_age[col_selection_age]

data_age

      valueCategory temporal agegroup  agegroup_type  incValue
790  cases_10y_mean     2022   0 - 16  agegroup_food     31.12
791  cases_10y_mean     2022  17 - 24  agegroup_food     22.53
792  cases_10y_mean     2022  25 - 44  agegroup_food     12.21
793  cases_10y_mean     2022  45 - 64  agegroup_food     12.02
794  cases_10y_mean     2022      65+  agegroup_food     17.73
795  cases_10y_mean     2022  unknown  agegroup_food       NaN
796  cases_10y_mean     2023   0 - 16  agegroup_food     31.94
797  cases_10y_mean     2023  17 - 24  agegroup_food     22.53
798  cases_10y_mean     2023  25 - 44  agegroup_food     12.63
799  cases_10y_mean     2023  45 - 64  agegroup_food     12.21
800  cases_10y_mean     2023      65+  agegroup_food     18.62
801  cases_10y_mean     2023  unknown  agegroup_food       NaN
802  cases_10y_mean     2024   0 - 16  agegroup_food     33.58
803  cases_10y_mean     2024  17 - 24  agegroup_food     23.61
804  cases_10y_mean     2024  25 - 44  agegroup_food     13.55
805  cases_10y_mean     2024  45 - 64  agegroup_food     12.78
806  cases_10y_mean     2024      65+  agegroup_food     19.72
807  cases_10y_mean     2024  unknown  agegroup_food       NaN
808  cases_10y_mean     2025   0 - 16  agegroup_food     35.14
809  cases_10y_mean     2025  17 - 24  agegroup_food     24.79
810  cases_10y_mean     2025  25 - 44  agegroup_food     14.36
811  cases_10y_mean     2025  45 - 64  agegroup_food     13.10
812  cases_10y_mean     2025      65+  agegroup_food     20.88
813  cases_10y_mean     2025  unknown  agegroup_food       NaN

In [20]:
# Exportieren des Datensatzes für Fälle pro Monat
data_age.to_csv("./export/reduziert_für_viz/data_salmonellosis_age.csv", index=False)