# Share 5 - BAG
## Campylobacteriosis
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/campylobacteriosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/campylobacteriosis/data

Werden monatlich geupdatet

Obligatorische Meldung

In [16]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [17]:
data = pd.read_csv("data/campylobacteriosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [18]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'value', 'pop',
       'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

## Reduktion des Datensatzes
### Altersverteilung
Variablen:
* valueCategory
* temporal
* agegroup != "all"
* agegroup_type
* incValue
* incValue gerundet

In [19]:
data_age = data.copy()
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [20]:
# Nur Zeilen in denen Agegroup nicht "all" ist

data_age = data_age[data_age["agegroup"] != "all"]
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
719,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,66.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
720,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,129.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
721,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,79.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
722,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,75.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
723,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,102.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
724,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
725,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,64.56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
726,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,125.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
727,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,77.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
728,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,74.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
729,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,102.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
730,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
731,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,63.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
732,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,124.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
733,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,76.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
734,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,75.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
735,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,104.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
736,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
737,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,63.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
738,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,124.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
739,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,77.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
740,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,76.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
741,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,108.48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
742,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [21]:
# Auswahl der Variablen
col_selection_age = ["valueCategory", "temporal", "agegroup", "agegroup_type", "incValue"]

col_selection_age

['valueCategory', 'temporal', 'agegroup', 'agegroup_type', 'incValue']

In [22]:
data_age = data_age[col_selection_age]

data_age

      valueCategory temporal agegroup  agegroup_type  incValue
719  cases_10y_mean     2022   0 - 16  agegroup_food     66.68
720  cases_10y_mean     2022  17 - 24  agegroup_food    129.40
721  cases_10y_mean     2022  25 - 44  agegroup_food     79.53
722  cases_10y_mean     2022  45 - 64  agegroup_food     75.56
723  cases_10y_mean     2022      65+  agegroup_food    102.75
724  cases_10y_mean     2022  unknown  agegroup_food       NaN
725  cases_10y_mean     2023   0 - 16  agegroup_food     64.56
726  cases_10y_mean     2023  17 - 24  agegroup_food    125.16
727  cases_10y_mean     2023  25 - 44  agegroup_food     77.21
728  cases_10y_mean     2023  45 - 64  agegroup_food     74.70
729  cases_10y_mean     2023      65+  agegroup_food    102.67
730  cases_10y_mean     2023  unknown  agegroup_food       NaN
731  cases_10y_mean     2024   0 - 16  agegroup_food     63.84
732  cases_10y_mean     2024  17 - 24  agegroup_food    124.13
733  cases_10y_mean     2024  25 - 44  agegroup_food     76.86
734  cases_10y_mean     2024  45 - 64  agegroup_food     75.16
735  cases_10y_mean     2024      65+  agegroup_food    104.28
736  cases_10y_mean     2024  unknown  agegroup_food       NaN
737  cases_10y_mean     2025   0 - 16  agegroup_food     63.93
738  cases_10y_mean     2025  17 - 24  agegroup_food    124.94
739  cases_10y_mean     2025  25 - 44  agegroup_food     77.30
740  cases_10y_mean     2025  45 - 64  agegroup_food     76.64
741  cases_10y_mean     2025      65+  agegroup_food    108.48
742  cases_10y_mean     2025  unknown  agegroup_food       NaN

In [23]:
data_age.insert(
    data_age.columns.get_loc("incValue") + 1,
    "incValue_rounded",
    data_age["incValue"].round(0)
)

data_age

,valueCategory,temporal,agegroup,agegroup_type,incValue,incValue_rounded
719,cases_10y_mean,2022,0 - 16,agegroup_food,66.68,67.0
720,cases_10y_mean,2022,17 - 24,agegroup_food,129.40,129.0
721,cases_10y_mean,2022,25 - 44,agegroup_food,79.53,80.0
722,cases_10y_mean,2022,45 - 64,agegroup_food,75.56,76.0
723,cases_10y_mean,2022,65+,agegroup_food,102.75,103.0
724,cases_10y_mean,2022,unknown,agegroup_food,NaN,NaN
725,cases_10y_mean,2023,0 - 16,agegroup_food,64.56,65.0
726,cases_10y_mean,2023,17 - 24,agegroup_food,125.16,125.0
727,cases_10y_mean,2023,25 - 44,agegroup_food,77.21,77.0
728,cases_10y_mean,2023,45 - 64,agegroup_food,74.70,75.0
729,cases_10y_mean,2023,65+,agegroup_food,102.67,103.0
730,cases_10y_mean,2023,unknown,agegroup_food,NaN,NaN
731,cases_10y_mean,2024,0 - 16,agegroup_food,63.84,64.0
732,cases_10y_mean,2024,17 - 24,agegroup_food,124.13,124.0
733,cases_10y_mean,2024,25 - 44,agegroup_food,76.86,77.0
734,cases_10y_mean,2024,45 - 64,agegroup_food,75.16,75.0
735,cases_10y_mean,2024,65+,agegroup_food,104.28,104.0
736,cases_10y_mean,2024,unknown,agegroup_food,NaN,NaN
737,cases_10y_mean,2025,0 - 16,agegroup_food,63.93,64.0
738,cases_10y_mean,2025,17 - 24,agegroup_food,124.94,125.0
739,cases_10y_mean,2025,25 - 44,agegroup_food,77.30,77.0
740,cases_10y_mean,2025,45 - 64,agegroup_food,76.64,77.0
741,cases_10y_mean,2025,65+,agegroup_food,108.48,108.0
742,cases_10y_mean,2025,unknown,agegroup_food,NaN,NaN

In [24]:
# Exportieren des Datensatzes
# data_age.to_csv("./export/reduziert_für_viz/campylobacteriosis/data_campylobacteriosis_age.csv", index=False)

### Georegion
Variablen:
* valueCategory
* temporal
* georegion
* georegion_type = "canton"
* (value)
* incValue 
* incValue gerundet
* kategorisierter incValue (12 Stufen)

In [25]:
data_geo = data.copy()
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [26]:
# Nur Zeilen in georegion_type = "canton"

data_geo = data_geo[data_geo["georegion_type"] == "canton"]
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,546.0,636362.0,85.80,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,25.0,15778.0,158.45,NaN,NaN,NaN,0.3,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,52.0,53691.0,96.85,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,958.0,1001281.0,95.68,NaN,NaN,NaN,12.8,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,417.0,278656.0,149.65,NaN,NaN,NaN,5.6,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
714,cases,2025,year,UR,canton,all,agegroup_food,all,20.0,38275.0,52.25,NaN,23.3,NaN,0.2,NaN,NaN,NaN,NaN,True
715,cases,2025,year,VD,canton,all,agegroup_food,all,1040.0,855106.0,121.62,NaN,952.7,NaN,12.0,NaN,NaN,NaN,NaN,True
716,cases,2025,year,VS,canton,all,agegroup_food,all,507.0,371288.0,136.55,NaN,462.0,NaN,5.8,NaN,NaN,NaN,NaN,True
717,cases,2025,year,ZG,canton,all,agegroup_food,all,116.0,133739.0,86.74,NaN,107.3,NaN,1.3,NaN,NaN,NaN,NaN,True
718,cases,2025,year,ZH,canton,all,agegroup_food,all,1379.0,1620020.0,85.12,NaN,1187.3,NaN,15.9,NaN,NaN,NaN,NaN,True

In [27]:
# Auswahl der Variablen
col_selection_geo = ["valueCategory", "temporal", "georegion", "georegion_type", "incValue"]
col_selection_geo

['valueCategory', 'temporal', 'georegion', 'georegion_type', 'incValue']

In [28]:
data_geo = data_geo[col_selection_geo]
data_geo

    valueCategory temporal georegion georegion_type  incValue
332         cases     2013        AG         canton     85.80
333         cases     2013        AI         canton    158.45
334         cases     2013        AR         canton     96.85
335         cases     2013        BE         canton     95.68
336         cases     2013        BL         canton    149.65
..            ...      ...       ...            ...       ...
714         cases     2025        UR         canton     52.25
715         cases     2025        VD         canton    121.62
716         cases     2025        VS         canton    136.55
717         cases     2025        ZG         canton     86.74
718         cases     2025        ZH         canton     85.12

[348 rows x 5 columns]

In [29]:
# Einfügen des gerundeten incValues

data_geo.insert(
    data_geo.columns.get_loc("incValue")+1,
    "incValue_rounded",
    data_geo["incValue"].round(0)
)

# Vorbereitung für Kategorisierung



data_geo["incValue_cat"] = (
    data_geo.groupby("temporal")["incValue"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=12,
            labels=[1,2,3,4,5,6,7,8,9,10,11,12]
        )
    )
)

data_geo

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51347/3520785640.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_geo["incValue_cat"] = (

,valueCategory,temporal,georegion,georegion_type,incValue,incValue_rounded,incValue_cat
332,cases,2013,AG,canton,85.80,86.0,5
333,cases,2013,AI,canton,158.45,158.0,12
334,cases,2013,AR,canton,96.85,97.0,6
335,cases,2013,BE,canton,95.68,96.0,6
336,cases,2013,BL,canton,149.65,150.0,12
...,...,...,...,...,...,...,...
714,cases,2025,UR,canton,52.25,52.0,1
715,cases,2025,VD,canton,121.62,122.0,9
716,cases,2025,VS,canton,136.55,137.0,11
717,cases,2025,ZG,canton,86.74,87.0,5
718,cases,2025,ZH,canton,85.12,85.0,4

In [38]:
# Exportieren des Datensatzes
#data_geo.to_csv("./export/reduziert_für_viz/campylobacteriosis/data_campylobacteriosis_georegion.csv", index=False)

### Geschlechtlicheverteilung
Variablen:
* valueCategory
* temporal
* sex != "all"
* value
* prct

In [39]:
data_sex = data.copy()

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [40]:
# Nur Datenpunkte zu Geschlecht

data_sex = data_sex[data_sex["sex"] != "all"]
data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
743,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,32962.0,NaN,NaN,NaN,NaN,NaN,45.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,39264.0,NaN,NaN,NaN,NaN,NaN,54.0,NaN,NaN,NaN,NaN,True
745,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,528.0,NaN,NaN,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
746,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,32486.0,NaN,NaN,NaN,NaN,NaN,45.1,NaN,NaN,NaN,NaN,True
747,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,39009.0,NaN,NaN,NaN,NaN,NaN,54.2,NaN,NaN,NaN,NaN,True
748,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,492.0,NaN,NaN,NaN,NaN,NaN,0.7,NaN,NaN,NaN,NaN,True
749,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,32688.0,NaN,NaN,NaN,NaN,NaN,44.9,NaN,NaN,NaN,NaN,True
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [41]:
col_selection_sex = ["valueCategory", "temporal", "sex", "value", "prct"]
col_selection_sex

['valueCategory', 'temporal', 'sex', 'value', 'prct']

In [42]:
data_sex = data_sex[col_selection_sex]
data_sex

        valueCategory temporal      sex    value  prct
743  cases_10y_cumsum     2022   female  32962.0  45.3
744  cases_10y_cumsum     2022     male  39264.0  54.0
745  cases_10y_cumsum     2022  unknown    528.0   0.7
746  cases_10y_cumsum     2023   female  32486.0  45.1
747  cases_10y_cumsum     2023     male  39009.0  54.2
748  cases_10y_cumsum     2023  unknown    492.0   0.7
749  cases_10y_cumsum     2024   female  32688.0  44.9
750  cases_10y_cumsum     2024     male  39656.0  54.5
751  cases_10y_cumsum     2024  unknown    457.0   0.6
752  cases_10y_cumsum     2025   female  33293.0  44.6
753  cases_10y_cumsum     2025     male  40954.0  54.9
754  cases_10y_cumsum     2025  unknown    400.0   0.5

In [ ]:
# Exportieren des Datensatzes
# data_sex.to_csv("./export/reduziert_für_viz/campylobacteriosis/data_campylobacteriosis_sex.csv", index=False)

### Krankheitstypen
Variablen:
* valueCategory
* temporal
* type != "all"
* value
* prct

In [44]:
data_types = data.copy()
data_types

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [37]:
data_types = data_types[data_types["type"] != "all"]
data_types

KeyError: 'type'

In [ ]:
col_selection_types = ["valueCategory", "temporal", "type", "value", "prct"]
col_selection_types

['valueCategory', 'temporal', 'type', 'value', 'prct']

In [ ]:
data_types = data_types[col_selection_types]
data_types

    valueCategory temporal                               type  value  prct
712         cases     2013                        enteritidis  366.0  28.8
713         cases     2013  monophasic_salmonella_typhimurium  204.0  16.1
714         cases     2013                             napoli   17.0   1.3
715         cases     2013                              other  467.0  36.7
716         cases     2013                            species   17.0   1.3
..            ...      ...                                ...    ...   ...
785         cases     2025  monophasic_salmonella_typhimurium  111.0   4.9
786         cases     2025                             napoli   63.0   2.8
787         cases     2025                              other  759.0  33.2
788         cases     2025                            species  170.0   7.4
789         cases     2025                        typhimurium  360.0  15.7

[78 rows x 5 columns]

In [ ]:
# Exportieren des Datensatzes
# data_types.to_csv("./export/reduziert_für_viz/data_salmonellosis_types.csv", index=False)

### Historische Entwicklung & Saisonalität
Variablen:
* valueCategory = "cases"
* temporal
* temporal_type = "month"
* value

--> Einzelner Datensatz pro Jahr

--> Trennen Monate & Jahre

In [45]:
data_temp = data.copy()
data_temp

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
750,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,39656.0,NaN,NaN,NaN,NaN,NaN,54.5,NaN,NaN,NaN,NaN,True
751,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,457.0,NaN,NaN,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,True
752,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,33293.0,NaN,NaN,NaN,NaN,NaN,44.6,NaN,NaN,NaN,NaN,True
753,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,40954.0,NaN,NaN,NaN,NaN,NaN,54.9,NaN,NaN,NaN,NaN,True
754,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,400.0,NaN,NaN,NaN,NaN,NaN,0.5,NaN,NaN,NaN,NaN,True

In [46]:
data_temp = data_temp[data_temp["valueCategory"]== "cases"]
data_temp = data_temp[data_temp["temporal_type"]== "month"]
data_temp

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,810.0,8176573.0,9.91,810.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,339.0,8176573.0,4.15,1149.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,299.0,8176573.0,3.66,1448.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,405.0,8176573.0,4.95,1853.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,488.0,8176573.0,5.97,2341.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,563.0,9091674.0,6.19,2252.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,851.0,9091674.0,9.36,3103.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,1096.0,9091674.0,12.05,4199.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,1280.0,9091674.0,14.08,5479.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,1392.0,9091674.0,15.31,6871.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True

In [47]:
col_selection_temp = ["valueCategory", "temporal", "value"]
col_selection_temp

['valueCategory', 'temporal', 'value']

In [48]:
data_temp = data_temp[col_selection_temp]
data_temp

    valueCategory  temporal   value
0           cases  2013-M01   810.0
1           cases  2013-M02   339.0
2           cases  2013-M03   299.0
3           cases  2013-M04   405.0
4           cases  2013-M05   488.0
..            ...       ...     ...
159         cases  2026-M04   563.0
160         cases  2026-M05   851.0
161         cases  2026-M06  1096.0
162         cases  2026-M07  1280.0
163         cases  2026-M08  1392.0

[164 rows x 3 columns]

In [49]:
data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
data_temp["year"] = data_temp["year"].astype(int)
data_temp["month"] = data_temp["month"].astype(int)
data_temp

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51347/2264127337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51347/2264127337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51347/2264127337.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["year"] = data_temp["year"].astype(int)
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51347/2264127337.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["month"] = data_temp["month"].astype(int)

    valueCategory  temporal   value  year  month
0           cases  2013-M01   810.0  2013      1
1           cases  2013-M02   339.0  2013      2
2           cases  2013-M03   299.0  2013      3
3           cases  2013-M04   405.0  2013      4
4           cases  2013-M05   488.0  2013      5
..            ...       ...     ...   ...    ...
159         cases  2026-M04   563.0  2026      4
160         cases  2026-M05   851.0  2026      5
161         cases  2026-M06  1096.0  2026      6
162         cases  2026-M07  1280.0  2026      7
163         cases  2026-M08  1392.0  2026      8

[164 rows x 5 columns]

In [50]:
data_temp_2 = data_temp.copy()
data_temp_2 = data_temp_2[data_temp_2["year"] == 2013]
data_temp_2

   valueCategory  temporal  value  year  month
0          cases  2013-M01  810.0  2013      1
1          cases  2013-M02  339.0  2013      2
2          cases  2013-M03  299.0  2013      3
3          cases  2013-M04  405.0  2013      4
4          cases  2013-M05  488.0  2013      5
5          cases  2013-M06  683.0  2013      6
6          cases  2013-M07  784.0  2013      7
7          cases  2013-M08  862.0  2013      8
8          cases  2013-M09  745.0  2013      9
9          cases  2013-M10  743.0  2013     10
10         cases  2013-M11  611.0  2013     11
11         cases  2013-M12  782.0  2013     12

In [51]:
# Vergleich der Monate (Saisonalität)
data_temp["value_cat"] = (
    data_temp.groupby("year")["value"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=4,
            labels=[1, 2, 3, 4]
        )
    )
)

data_temp

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51347/4145613601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["value_cat"] = (

    valueCategory  temporal   value  year  month value_cat
0           cases  2013-M01   810.0  2013      1         4
1           cases  2013-M02   339.0  2013      2         1
2           cases  2013-M03   299.0  2013      3         1
3           cases  2013-M04   405.0  2013      4         1
4           cases  2013-M05   488.0  2013      5         2
..            ...       ...     ...   ...    ...       ...
159         cases  2026-M04   563.0  2026      4         1
160         cases  2026-M05   851.0  2026      5         2
161         cases  2026-M06  1096.0  2026      6         3
162         cases  2026-M07  1280.0  2026      7         4
163         cases  2026-M08  1392.0  2026      8         4

[164 rows x 6 columns]

In [ ]:
# Exportieren des Datensatzes
# data_temp.to_csv("./export/reduziert_für_viz/campylobacteriosis/data_campylobacteriosis_historisch.csv", index=False)