# Share 5 - BAG
## Shigellose
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/shigellosis/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/shigellosis/data

Werden monatlich geupdatet

Obligatorische Meldung

In [1]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [2]:
data = pd.read_csv("data/shigellosis/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [3]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'value', 'pop',
       'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

## Reduktion des Datensatzes
### Altersverteilung
Variablen:
* valueCategory
* temporal
* agegroup != "all"
* agegroup_type
* incValue
* incValue gerundet

In [4]:
data_age = data.copy()
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [5]:
# Nur Zeilen in denen Agegroup nicht "all" ist

data_age = data_age[data_age["agegroup"] != "all"]
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
709,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
710,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
711,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,2.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
712,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,1.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
713,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
714,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
715,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
716,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
717,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,2.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
718,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,1.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
719,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
720,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
721,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
722,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
723,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,3.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
724,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,2.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
725,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
726,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
727,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,NaN,NaN,1.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
728,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,NaN,NaN,2.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
729,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,NaN,NaN,3.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
730,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,NaN,NaN,1.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
731,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,NaN,NaN,0.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
732,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [6]:
# Auswahl der Variablen
col_selection_age = ["valueCategory", "temporal", "agegroup", "agegroup_type", "incValue"]

col_selection_age

['valueCategory', 'temporal', 'agegroup', 'agegroup_type', 'incValue']

In [7]:
data_age = data_age[col_selection_age]

data_age

      valueCategory temporal agegroup  agegroup_type  incValue
709  cases_10y_mean     2022   0 - 16  agegroup_food      1.23
710  cases_10y_mean     2022  17 - 24  agegroup_food      2.16
711  cases_10y_mean     2022  25 - 44  agegroup_food      2.82
712  cases_10y_mean     2022  45 - 64  agegroup_food      1.96
713  cases_10y_mean     2022      65+  agegroup_food      0.81
714  cases_10y_mean     2022  unknown  agegroup_food       NaN
715  cases_10y_mean     2023   0 - 16  agegroup_food      1.18
716  cases_10y_mean     2023  17 - 24  agegroup_food      2.09
717  cases_10y_mean     2023  25 - 44  agegroup_food      2.94
718  cases_10y_mean     2023  45 - 64  agegroup_food      1.99
719  cases_10y_mean     2023      65+  agegroup_food      0.81
720  cases_10y_mean     2023  unknown  agegroup_food       NaN
721  cases_10y_mean     2024   0 - 16  agegroup_food      1.14
722  cases_10y_mean     2024  17 - 24  agegroup_food      2.03
723  cases_10y_mean     2024  25 - 44  agegroup_food      3.11
724  cases_10y_mean     2024  45 - 64  agegroup_food      2.01
725  cases_10y_mean     2024      65+  agegroup_food      0.86
726  cases_10y_mean     2024  unknown  agegroup_food       NaN
727  cases_10y_mean     2025   0 - 16  agegroup_food      1.16
728  cases_10y_mean     2025  17 - 24  agegroup_food      2.10
729  cases_10y_mean     2025  25 - 44  agegroup_food      3.25
730  cases_10y_mean     2025  45 - 64  agegroup_food      1.98
731  cases_10y_mean     2025      65+  agegroup_food      0.86
732  cases_10y_mean     2025  unknown  agegroup_food       NaN

In [8]:
data_age.insert(
    data_age.columns.get_loc("incValue") + 1,
    "incValue_rounded",
    data_age["incValue"].round(0)
)

data_age

,valueCategory,temporal,agegroup,agegroup_type,incValue,incValue_rounded
709,cases_10y_mean,2022,0 - 16,agegroup_food,1.23,1.0
710,cases_10y_mean,2022,17 - 24,agegroup_food,2.16,2.0
711,cases_10y_mean,2022,25 - 44,agegroup_food,2.82,3.0
712,cases_10y_mean,2022,45 - 64,agegroup_food,1.96,2.0
713,cases_10y_mean,2022,65+,agegroup_food,0.81,1.0
714,cases_10y_mean,2022,unknown,agegroup_food,NaN,NaN
715,cases_10y_mean,2023,0 - 16,agegroup_food,1.18,1.0
716,cases_10y_mean,2023,17 - 24,agegroup_food,2.09,2.0
717,cases_10y_mean,2023,25 - 44,agegroup_food,2.94,3.0
718,cases_10y_mean,2023,45 - 64,agegroup_food,1.99,2.0
719,cases_10y_mean,2023,65+,agegroup_food,0.81,1.0
720,cases_10y_mean,2023,unknown,agegroup_food,NaN,NaN
721,cases_10y_mean,2024,0 - 16,agegroup_food,1.14,1.0
722,cases_10y_mean,2024,17 - 24,agegroup_food,2.03,2.0
723,cases_10y_mean,2024,25 - 44,agegroup_food,3.11,3.0
724,cases_10y_mean,2024,45 - 64,agegroup_food,2.01,2.0
725,cases_10y_mean,2024,65+,agegroup_food,0.86,1.0
726,cases_10y_mean,2024,unknown,agegroup_food,NaN,NaN
727,cases_10y_mean,2025,0 - 16,agegroup_food,1.16,1.0
728,cases_10y_mean,2025,17 - 24,agegroup_food,2.10,2.0
729,cases_10y_mean,2025,25 - 44,agegroup_food,3.25,3.0
730,cases_10y_mean,2025,45 - 64,agegroup_food,1.98,2.0
731,cases_10y_mean,2025,65+,agegroup_food,0.86,1.0
732,cases_10y_mean,2025,unknown,agegroup_food,NaN,NaN

In [ ]:
# Exportieren des Datensatzes
# data_age.to_csv("./export/reduziert_für_viz/shigellosis/data_shigellosis_age.csv", index=False)

### Georegion
Variablen:
* valueCategory
* temporal
* georegion
* georegion_type = "canton"
* (value)
* incValue 
* incValue gerundet
* kategorisierter incValue (12 Stufen)

In [10]:
data_geo = data.copy()
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [11]:
# Nur Zeilen in georegion_type = "canton"

data_geo = data_geo[data_geo["georegion_type"] == "canton"]
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,11.0,636362.0,1.73,NaN,NaN,NaN,7.5,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,0.0,15778.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,0.0,53691.0,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,9.0,1001281.0,0.90,NaN,NaN,NaN,6.1,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,7.0,278656.0,2.51,NaN,NaN,NaN,4.8,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,cases,2025,year,UR,canton,all,agegroup_food,all,0.0,38275.0,0.00,NaN,0.3,NaN,0.0,NaN,NaN,NaN,NaN,True
705,cases,2025,year,VD,canton,all,agegroup_food,all,37.0,855106.0,4.33,NaN,34.0,NaN,15.9,NaN,NaN,NaN,NaN,True
706,cases,2025,year,VS,canton,all,agegroup_food,all,10.0,371288.0,2.69,NaN,7.3,NaN,4.3,NaN,NaN,NaN,NaN,True
707,cases,2025,year,ZG,canton,all,agegroup_food,all,4.0,133739.0,2.99,NaN,4.7,NaN,1.7,NaN,NaN,NaN,NaN,True
708,cases,2025,year,ZH,canton,all,agegroup_food,all,37.0,1620020.0,2.28,NaN,37.0,NaN,15.9,NaN,NaN,NaN,NaN,True

In [12]:
# Auswahl der Variablen
col_selection_geo = ["valueCategory", "temporal", "georegion", "georegion_type", "incValue"]
col_selection_geo

['valueCategory', 'temporal', 'georegion', 'georegion_type', 'incValue']

In [13]:
data_geo = data_geo[col_selection_geo]
data_geo

    valueCategory temporal georegion georegion_type  incValue
332         cases     2013        AG         canton      1.73
333         cases     2013        AI         canton      0.00
334         cases     2013        AR         canton      0.00
335         cases     2013        BE         canton      0.90
336         cases     2013        BL         canton      2.51
..            ...      ...       ...            ...       ...
704         cases     2025        UR         canton      0.00
705         cases     2025        VD         canton      4.33
706         cases     2025        VS         canton      2.69
707         cases     2025        ZG         canton      2.99
708         cases     2025        ZH         canton      2.28

[338 rows x 5 columns]

In [14]:
# Einfügen des gerundeten incValues

data_geo.insert(
    data_geo.columns.get_loc("incValue")+1,
    "incValue_rounded",
    data_geo["incValue"].round(0)
)

# Vorbereitung für Kategorisierung



data_geo["incValue_cat"] = (
    data_geo.groupby("temporal")["incValue"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=12,
            labels=[1,2,3,4,5,6,7,8,9,10,11,12]
        )
    )
)

data_geo

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51403/3520785640.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_geo["incValue_cat"] = (

,valueCategory,temporal,georegion,georegion_type,incValue,incValue_rounded,incValue_cat
332,cases,2013,AG,canton,1.73,2.0,5
333,cases,2013,AI,canton,0.00,0.0,1
334,cases,2013,AR,canton,0.00,0.0,1
335,cases,2013,BE,canton,0.90,1.0,3
336,cases,2013,BL,canton,2.51,3.0,7
...,...,...,...,...,...,...,...
704,cases,2025,UR,canton,0.00,0.0,1
705,cases,2025,VD,canton,4.33,4.0,8
706,cases,2025,VS,canton,2.69,3.0,5
707,cases,2025,ZG,canton,2.99,3.0,5
708,cases,2025,ZH,canton,2.28,2.0,4

In [ ]:
# Exportieren des Datensatzes
# data_geo.to_csv("./export/reduziert_für_viz/shigellosis/data_shigellosis_georegion.csv", index=False)

### Geschlechtlicheverteilung
Variablen:
* valueCategory
* temporal
* sex != "all"
* value
* prct

In [16]:
data_sex = data.copy()

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [17]:
# Nur Datenpunkte zu Geschlecht

data_sex = data_sex[data_sex["sex"] != "all"]
data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
733,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,704.0,NaN,NaN,NaN,NaN,NaN,43.9,NaN,NaN,NaN,NaN,True
734,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,897.0,NaN,NaN,NaN,NaN,NaN,55.9,NaN,NaN,NaN,NaN,True
735,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,3.0,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,NaN,True
736,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,695.0,NaN,NaN,NaN,NaN,NaN,42.2,NaN,NaN,NaN,NaN,True
737,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,947.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
738,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,4.0,NaN,NaN,NaN,NaN,NaN,0.2,NaN,NaN,NaN,NaN,True
739,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,723.0,NaN,NaN,NaN,NaN,NaN,42.4,NaN,NaN,NaN,NaN,True
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [18]:
col_selection_sex = ["valueCategory", "temporal", "sex", "value", "prct"]
col_selection_sex

['valueCategory', 'temporal', 'sex', 'value', 'prct']

In [19]:
data_sex = data_sex[col_selection_sex]
data_sex

        valueCategory temporal      sex   value  prct
733  cases_10y_cumsum     2022   female   704.0  43.9
734  cases_10y_cumsum     2022     male   897.0  55.9
735  cases_10y_cumsum     2022  unknown     3.0   0.2
736  cases_10y_cumsum     2023   female   695.0  42.2
737  cases_10y_cumsum     2023     male   947.0  57.5
738  cases_10y_cumsum     2023  unknown     4.0   0.2
739  cases_10y_cumsum     2024   female   723.0  42.4
740  cases_10y_cumsum     2024     male   979.0  57.5
741  cases_10y_cumsum     2024  unknown     2.0   0.1
742  cases_10y_cumsum     2025   female   748.0  42.6
743  cases_10y_cumsum     2025     male  1007.0  57.3
744  cases_10y_cumsum     2025  unknown     2.0   0.1

In [ ]:
# Exportieren des Datensatzes
# data_sex.to_csv("./export/reduziert_für_viz/shigellosis/data_shigellosis_sex.csv", index=False)

### Krankheitstypen
Variablen:
* valueCategory
* temporal
* type != "all"
* value
* prct

In [21]:
data_types = data.copy()
data_types

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [22]:
data_types = data_types[data_types["type"] != "all"]
data_types

KeyError: 'type'

In [23]:
col_selection_types = ["valueCategory", "temporal", "type", "value", "prct"]
col_selection_types

['valueCategory', 'temporal', 'type', 'value', 'prct']

In [24]:
data_types = data_types[col_selection_types]
data_types

KeyError: "['type'] not in index"

In [ ]:
# Exportieren des Datensatzes
# data_types.to_csv("./export/reduziert_für_viz/data_salmonellosis_types.csv", index=False)

### Historische Entwicklung & Saisonalität
Variablen:
* valueCategory = "cases"
* temporal
* temporal_type = "month"
* value

--> Einzelner Datensatz pro Jahr

--> Trennen Monate & Jahre

In [25]:
data_temp = data.copy()
data_temp

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
740,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,979.0,NaN,NaN,NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,True
741,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
742,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,748.0,NaN,NaN,NaN,NaN,NaN,42.6,NaN,NaN,NaN,NaN,True
743,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,1007.0,NaN,NaN,NaN,NaN,NaN,57.3,NaN,NaN,NaN,NaN,True
744,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,2.0,NaN,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [26]:
data_temp = data_temp[data_temp["valueCategory"]== "cases"]
data_temp = data_temp[data_temp["temporal_type"]== "month"]
data_temp

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,value,pop,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,15.0,8176573.0,0.18,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,11.0,8176573.0,0.13,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,13.0,8176573.0,0.16,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,12.0,8176573.0,0.15,51.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,4.0,8176573.0,0.05,55.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,17.0,9091674.0,0.19,70.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,18.0,9091674.0,0.20,88.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,23.0,9091674.0,0.25,111.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,23.0,9091674.0,0.25,134.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,27.0,9091674.0,0.30,161.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True

In [27]:
col_selection_temp = ["valueCategory", "temporal", "value"]
col_selection_temp

['valueCategory', 'temporal', 'value']

In [28]:
data_temp = data_temp[col_selection_temp]
data_temp

    valueCategory  temporal  value
0           cases  2013-M01   15.0
1           cases  2013-M02   11.0
2           cases  2013-M03   13.0
3           cases  2013-M04   12.0
4           cases  2013-M05    4.0
..            ...       ...    ...
159         cases  2026-M04   17.0
160         cases  2026-M05   18.0
161         cases  2026-M06   23.0
162         cases  2026-M07   23.0
163         cases  2026-M08   27.0

[164 rows x 3 columns]

In [29]:
data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
data_temp["year"] = data_temp["year"].astype(int)
data_temp["month"] = data_temp["month"].astype(int)
data_temp

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51403/2264127337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51403/2264127337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51403/2264127337.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["year"] = data_temp["year"].astype(int)
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51403/2264127337.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["month"] = data_temp["month"].astype(int)

    valueCategory  temporal  value  year  month
0           cases  2013-M01   15.0  2013      1
1           cases  2013-M02   11.0  2013      2
2           cases  2013-M03   13.0  2013      3
3           cases  2013-M04   12.0  2013      4
4           cases  2013-M05    4.0  2013      5
..            ...       ...    ...   ...    ...
159         cases  2026-M04   17.0  2026      4
160         cases  2026-M05   18.0  2026      5
161         cases  2026-M06   23.0  2026      6
162         cases  2026-M07   23.0  2026      7
163         cases  2026-M08   27.0  2026      8

[164 rows x 5 columns]

In [30]:
data_temp_2 = data_temp.copy()
data_temp_2 = data_temp_2[data_temp_2["year"] == 2013]
data_temp_2

   valueCategory  temporal  value  year  month
0          cases  2013-M01   15.0  2013      1
1          cases  2013-M02   11.0  2013      2
2          cases  2013-M03   13.0  2013      3
3          cases  2013-M04   12.0  2013      4
4          cases  2013-M05    4.0  2013      5
5          cases  2013-M06    6.0  2013      6
6          cases  2013-M07   13.0  2013      7
7          cases  2013-M08   23.0  2013      8
8          cases  2013-M09   14.0  2013      9
9          cases  2013-M10    6.0  2013     10
10         cases  2013-M11   17.0  2013     11
11         cases  2013-M12   13.0  2013     12

In [31]:
# Vergleich der Monate (Saisonalität)
data_temp["value_cat"] = (
    data_temp.groupby("year")["value"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=4,
            labels=[1, 2, 3, 4]
        )
    )
)

data_temp

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_51403/4145613601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["value_cat"] = (

    valueCategory  temporal  value  year  month value_cat
0           cases  2013-M01   15.0  2013      1         3
1           cases  2013-M02   11.0  2013      2         2
2           cases  2013-M03   13.0  2013      3         2
3           cases  2013-M04   12.0  2013      4         2
4           cases  2013-M05    4.0  2013      5         1
..            ...       ...    ...   ...    ...       ...
159         cases  2026-M04   17.0  2026      4         1
160         cases  2026-M05   18.0  2026      5         1
161         cases  2026-M06   23.0  2026      6         3
162         cases  2026-M07   23.0  2026      7         3
163         cases  2026-M08   27.0  2026      8         4

[164 rows x 6 columns]

In [ ]:
# Exportieren des Datensatzes
# data_temp.to_csv("./export/reduziert_für_viz/shigellosis/data_shigellosis_historisch.csv", index=False)