# Share 5 - BAG
## EHEC - Enterohämorrhagische Escherichia coli-Infektion
* Übersicht: https://www.idd.bag.admin.ch/de/diseases/ehec/overview
* Daten: https://www.idd.bag.admin.ch/de/diseases/ehec/data

Werden monatlich geupdatet

Oblig. Meldung

In [1]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

### Daten hereinladen

In [2]:
data = pd.read_csv("data/ehec/data.csv")

data

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [3]:
data.columns

Index(['valueCategory', 'temporal', 'temporal_type', 'georegion',
       'georegion_type', 'agegroup', 'agegroup_type', 'sex', 'type', 'value',
       'pop', 'incValue', 'valueYearCumSum', 'valueMean3y', 'trend', 'prct',
       'deltaValue', 'deltaIncValue', 'incValuePrctChange', 'valueMean5y',
       'dataComplete'],
      dtype='object')

## Reduktion des Datensatzes
### Altersverteilung
Variablen:
* valueCategory
* temporal
* agegroup != "all"
* agegroup_type
* incValue
* incValue gerundet

In [4]:
data_age = data.copy()
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [5]:
# Nur Zeilen in denen Agegroup nicht "all" ist

data_age = data_age[data_age["agegroup"] != "all"]
data_age

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
735,cases_10y_mean,2022,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,9.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
736,cases_10y_mean,2022,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,6.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
737,cases_10y_mean,2022,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,5.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
738,cases_10y_mean,2022,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,5.73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
739,cases_10y_mean,2022,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,11.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
740,cases_10y_mean,2022,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
741,cases_10y_mean,2023,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,10.87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
742,cases_10y_mean,2023,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,7.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
743,cases_10y_mean,2023,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,6.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
744,cases_10y_mean,2023,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,6.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
745,cases_10y_mean,2023,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,13.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
746,cases_10y_mean,2023,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
747,cases_10y_mean,2024,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,12.28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
748,cases_10y_mean,2024,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,8.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
749,cases_10y_mean,2024,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,7.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
750,cases_10y_mean,2024,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,7.83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
751,cases_10y_mean,2024,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,15.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
752,cases_10y_mean,2024,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
753,cases_10y_mean,2025,year,CHFL,CHFL,0 - 16,agegroup_food,all,all,NaN,...,13.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
754,cases_10y_mean,2025,year,CHFL,CHFL,17 - 24,agegroup_food,all,all,NaN,...,10.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
755,cases_10y_mean,2025,year,CHFL,CHFL,25 - 44,agegroup_food,all,all,NaN,...,8.34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
756,cases_10y_mean,2025,year,CHFL,CHFL,45 - 64,agegroup_food,all,all,NaN,...,8.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
757,cases_10y_mean,2025,year,CHFL,CHFL,65+,agegroup_food,all,all,NaN,...,17.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
758,cases_10y_mean,2025,year,CHFL,CHFL,unknown,agegroup_food,all,all,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [6]:
# Auswahl der Variablen
col_selection_age = ["valueCategory", "temporal", "agegroup", "agegroup_type", "incValue"]

col_selection_age

['valueCategory', 'temporal', 'agegroup', 'agegroup_type', 'incValue']

In [7]:
data_age = data_age[col_selection_age]

data_age

      valueCategory temporal agegroup  agegroup_type  incValue
735  cases_10y_mean     2022   0 - 16  agegroup_food      9.62
736  cases_10y_mean     2022  17 - 24  agegroup_food      6.17
737  cases_10y_mean     2022  25 - 44  agegroup_food      5.39
738  cases_10y_mean     2022  45 - 64  agegroup_food      5.73
739  cases_10y_mean     2022      65+  agegroup_food     11.69
740  cases_10y_mean     2022  unknown  agegroup_food       NaN
741  cases_10y_mean     2023   0 - 16  agegroup_food     10.87
742  cases_10y_mean     2023  17 - 24  agegroup_food      7.45
743  cases_10y_mean     2023  25 - 44  agegroup_food      6.33
744  cases_10y_mean     2023  45 - 64  agegroup_food      6.82
745  cases_10y_mean     2023      65+  agegroup_food     13.72
746  cases_10y_mean     2023  unknown  agegroup_food       NaN
747  cases_10y_mean     2024   0 - 16  agegroup_food     12.28
748  cases_10y_mean     2024  17 - 24  agegroup_food      8.85
749  cases_10y_mean     2024  25 - 44  agegroup_food      7.42
750  cases_10y_mean     2024  45 - 64  agegroup_food      7.83
751  cases_10y_mean     2024      65+  agegroup_food     15.99
752  cases_10y_mean     2024  unknown  agegroup_food       NaN
753  cases_10y_mean     2025   0 - 16  agegroup_food     13.23
754  cases_10y_mean     2025  17 - 24  agegroup_food     10.14
755  cases_10y_mean     2025  25 - 44  agegroup_food      8.34
756  cases_10y_mean     2025  45 - 64  agegroup_food      8.99
757  cases_10y_mean     2025      65+  agegroup_food     17.91
758  cases_10y_mean     2025  unknown  agegroup_food       NaN

In [8]:
data_age.insert(
    data_age.columns.get_loc("incValue") + 1,
    "incValue_rounded",
    data_age["incValue"].round(0)
)

data_age

,valueCategory,temporal,agegroup,agegroup_type,incValue,incValue_rounded
735,cases_10y_mean,2022,0 - 16,agegroup_food,9.62,10.0
736,cases_10y_mean,2022,17 - 24,agegroup_food,6.17,6.0
737,cases_10y_mean,2022,25 - 44,agegroup_food,5.39,5.0
738,cases_10y_mean,2022,45 - 64,agegroup_food,5.73,6.0
739,cases_10y_mean,2022,65+,agegroup_food,11.69,12.0
740,cases_10y_mean,2022,unknown,agegroup_food,NaN,NaN
741,cases_10y_mean,2023,0 - 16,agegroup_food,10.87,11.0
742,cases_10y_mean,2023,17 - 24,agegroup_food,7.45,7.0
743,cases_10y_mean,2023,25 - 44,agegroup_food,6.33,6.0
744,cases_10y_mean,2023,45 - 64,agegroup_food,6.82,7.0
745,cases_10y_mean,2023,65+,agegroup_food,13.72,14.0
746,cases_10y_mean,2023,unknown,agegroup_food,NaN,NaN
747,cases_10y_mean,2024,0 - 16,agegroup_food,12.28,12.0
748,cases_10y_mean,2024,17 - 24,agegroup_food,8.85,9.0
749,cases_10y_mean,2024,25 - 44,agegroup_food,7.42,7.0
750,cases_10y_mean,2024,45 - 64,agegroup_food,7.83,8.0
751,cases_10y_mean,2024,65+,agegroup_food,15.99,16.0
752,cases_10y_mean,2024,unknown,agegroup_food,NaN,NaN
753,cases_10y_mean,2025,0 - 16,agegroup_food,13.23,13.0
754,cases_10y_mean,2025,17 - 24,agegroup_food,10.14,10.0
755,cases_10y_mean,2025,25 - 44,agegroup_food,8.34,8.0
756,cases_10y_mean,2025,45 - 64,agegroup_food,8.99,9.0
757,cases_10y_mean,2025,65+,agegroup_food,17.91,18.0
758,cases_10y_mean,2025,unknown,agegroup_food,NaN,NaN

In [9]:
# Exportieren des Datensatzes
# data_age.to_csv("./export/reduziert_für_viz/ehec/data_ehec_age.csv", index=False)

### Georegion
Variablen:
* valueCategory
* temporal
* georegion
* georegion_type = "canton"
* (value)
* incValue 
* incValue gerundet
* kategorisierter incValue (12 Stufen)

In [10]:
data_geo = data.copy()
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [11]:
# Nur Zeilen in georegion_type = "canton"

data_geo = data_geo[data_geo["georegion_type"] == "canton"]
data_geo

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
332,cases,2013,year,AG,canton,all,agegroup_food,all,all,9.0,...,1.41,NaN,NaN,NaN,11.0,NaN,NaN,NaN,NaN,True
333,cases,2013,year,AI,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
334,cases,2013,year,AR,canton,all,agegroup_food,all,all,0.0,...,0.00,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
335,cases,2013,year,BE,canton,all,agegroup_food,all,all,13.0,...,1.30,NaN,NaN,NaN,15.9,NaN,NaN,NaN,NaN,True
336,cases,2013,year,BL,canton,all,agegroup_food,all,all,6.0,...,2.15,NaN,NaN,NaN,7.3,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,cases,2025,year,UR,canton,all,agegroup_food,all,all,6.0,...,15.68,NaN,7.0,NaN,0.4,NaN,NaN,NaN,NaN,True
705,cases,2025,year,VD,canton,all,agegroup_food,all,all,196.0,...,22.92,NaN,179.0,NaN,13.6,NaN,NaN,NaN,NaN,True
706,cases,2025,year,VS,canton,all,agegroup_food,all,all,81.0,...,21.82,NaN,59.7,NaN,5.6,NaN,NaN,NaN,NaN,True
707,cases,2025,year,ZG,canton,all,agegroup_food,all,all,23.0,...,17.20,NaN,22.7,NaN,1.6,NaN,NaN,NaN,NaN,True
708,cases,2025,year,ZH,canton,all,agegroup_food,all,all,240.0,...,14.81,NaN,215.7,NaN,16.7,NaN,NaN,NaN,NaN,True

In [12]:
# Auswahl der Variablen
col_selection_geo = ["valueCategory", "temporal", "georegion", "georegion_type", "incValue"]
col_selection_geo

['valueCategory', 'temporal', 'georegion', 'georegion_type', 'incValue']

In [13]:
data_geo = data_geo[col_selection_geo]
data_geo

    valueCategory temporal georegion georegion_type  incValue
332         cases     2013        AG         canton      1.41
333         cases     2013        AI         canton      0.00
334         cases     2013        AR         canton      0.00
335         cases     2013        BE         canton      1.30
336         cases     2013        BL         canton      2.15
..            ...      ...       ...            ...       ...
704         cases     2025        UR         canton     15.68
705         cases     2025        VD         canton     22.92
706         cases     2025        VS         canton     21.82
707         cases     2025        ZG         canton     17.20
708         cases     2025        ZH         canton     14.81

[338 rows x 5 columns]

In [14]:
# Einfügen des gerundeten incValues

data_geo.insert(
    data_geo.columns.get_loc("incValue")+1,
    "incValue_rounded",
    data_geo["incValue"].round(0)
)

# Vorbereitung für Kategorisierung



data_geo["incValue_cat"] = (
    data_geo.groupby("temporal")["incValue"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=12,
            labels=[1,2,3,4,5,6,7,8,9,10,11,12]
        )
    )
)

data_geo

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_53627/3520785640.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_geo["incValue_cat"] = (

,valueCategory,temporal,georegion,georegion_type,incValue,incValue_rounded,incValue_cat
332,cases,2013,AG,canton,1.41,1.0,4
333,cases,2013,AI,canton,0.00,0.0,1
334,cases,2013,AR,canton,0.00,0.0,1
335,cases,2013,BE,canton,1.30,1.0,4
336,cases,2013,BL,canton,2.15,2.0,6
...,...,...,...,...,...,...,...
704,cases,2025,UR,canton,15.68,16.0,7
705,cases,2025,VD,canton,22.92,23.0,10
706,cases,2025,VS,canton,21.82,22.0,10
707,cases,2025,ZG,canton,17.20,17.0,7
708,cases,2025,ZH,canton,14.81,15.0,6

In [15]:
# Exportieren des Datensatzes
# data_geo.to_csv("./export/reduziert_für_viz/ehec/data_ehec_georegion.csv", index=False)

### Geschlechtlicheverteilung
Variablen:
* valueCategory
* temporal
* sex != "all"
* value
* prct

In [16]:
data_sex = data.copy()

data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [17]:
# Nur Datenpunkte zu Geschlecht

data_sex = data_sex[data_sex["sex"] != "all"]
data_sex

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
759,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,female,all,3600.0,...,NaN,NaN,NaN,NaN,55.8,NaN,NaN,NaN,NaN,True
760,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,male,all,2843.0,...,NaN,NaN,NaN,NaN,44.1,NaN,NaN,NaN,NaN,True
761,cases_10y_cumsum,2022,year,CHFL,CHFL,all,agegroup_food,unknown,all,3.0,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,True
762,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,female,all,4228.0,...,NaN,NaN,NaN,NaN,55.6,NaN,NaN,NaN,NaN,True
763,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,male,all,3369.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
764,cases_10y_cumsum,2023,year,CHFL,CHFL,all,agegroup_food,unknown,all,5.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
765,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,female,all,4931.0,...,NaN,NaN,NaN,NaN,55.6,NaN,NaN,NaN,NaN,True
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [18]:
col_selection_sex = ["valueCategory", "temporal", "sex", "value", "prct"]
col_selection_sex

['valueCategory', 'temporal', 'sex', 'value', 'prct']

In [19]:
data_sex = data_sex[col_selection_sex]
data_sex

        valueCategory temporal      sex   value  prct
759  cases_10y_cumsum     2022   female  3600.0  55.8
760  cases_10y_cumsum     2022     male  2843.0  44.1
761  cases_10y_cumsum     2022  unknown     3.0   0.0
762  cases_10y_cumsum     2023   female  4228.0  55.6
763  cases_10y_cumsum     2023     male  3369.0  44.3
764  cases_10y_cumsum     2023  unknown     5.0   0.1
765  cases_10y_cumsum     2024   female  4931.0  55.6
766  cases_10y_cumsum     2024     male  3928.0  44.3
767  cases_10y_cumsum     2024  unknown    10.0   0.1
768  cases_10y_cumsum     2025   female  5569.0  55.7
769  cases_10y_cumsum     2025     male  4427.0  44.2
770  cases_10y_cumsum     2025  unknown    11.0   0.1

In [20]:
# Exportieren des Datensatzes
#data_sex.to_csv("./export/reduziert_für_viz/ehec/data_ehec_sex.csv", index=False)

### Krankheitstypen
Variablen:
* valueCategory
* temporal
* type != "all"
* value
* prct

In [21]:
data_types = data.copy()
data_types

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [22]:
data_types = data_types[data_types["type"] != "all"]
data_types

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
709,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,hus,11.0,...,0.13,NaN,NaN,NaN,13.3,NaN,NaN,NaN,NaN,True
710,cases,2013,year,CHFL,CHFL,all,agegroup_food,all,non-hus,72.0,...,0.88,NaN,NaN,NaN,86.7,NaN,NaN,NaN,NaN,True
711,cases,2014,year,CHFL,CHFL,all,agegroup_food,all,hus,11.0,...,0.13,NaN,NaN,NaN,8.8,NaN,NaN,NaN,NaN,True
712,cases,2014,year,CHFL,CHFL,all,agegroup_food,all,non-hus,114.0,...,1.38,NaN,NaN,NaN,91.2,NaN,NaN,NaN,NaN,True
713,cases,2015,year,CHFL,CHFL,all,agegroup_food,all,hus,14.0,...,0.17,NaN,12.0,NaN,4.5,NaN,NaN,NaN,NaN,True
714,cases,2015,year,CHFL,CHFL,all,agegroup_food,all,non-hus,294.0,...,3.52,NaN,160.0,NaN,95.5,NaN,NaN,NaN,NaN,True
715,cases,2016,year,CHFL,CHFL,all,agegroup_food,all,hus,16.0,...,0.19,NaN,13.7,NaN,3.1,NaN,NaN,NaN,NaN,True
716,cases,2016,year,CHFL,CHFL,all,agegroup_food,all,non-hus,494.0,...,5.84,NaN,300.7,NaN,96.9,NaN,NaN,NaN,NaN,True
717,cases,2017,year,CHFL,CHFL,all,agegroup_food,all,hus,19.0,...,0.22,NaN,16.3,NaN,2.6,NaN,NaN,NaN,NaN,True
718,cases,2017,year,CHFL,CHFL,all,agegroup_food,all,non-hus,702.0,...,8.24,NaN,496.7,NaN,97.4,NaN,NaN,NaN,NaN,True
719,cases,2018,year,CHFL,CHFL,all,agegroup_food,all,hus,23.0,...,0.27,NaN,19.3,NaN,2.6,NaN,NaN,NaN,NaN,True
720,cases,2018,year,CHFL,CHFL,all,agegroup_food,all,non-hus,855.0,...,9.96,NaN,683.7,NaN,97.4,NaN,NaN,NaN,NaN,True
721,cases,2019,year,CHFL,CHFL,all,agegroup_food,all,hus,20.0,...,0.23,NaN,20.7,NaN,2.1,NaN,NaN,NaN,NaN,True
722,cases,2019,year,CHFL,CHFL,all,agegroup_food,all,non-hus,950.0,...,10.99,NaN,835.7,NaN,97.9,NaN,NaN,NaN,NaN,True
723,cases,2020,year,CHFL,CHFL,all,agegroup_food,all,hus,18.0,...,0.21,NaN,20.3,NaN,2.6,NaN,NaN,NaN,NaN,True
724,cases,2020,year,CHFL,CHFL,all,agegroup_food,all,non-hus,681.0,...,7.82,NaN,828.7,NaN,97.4,NaN,NaN,NaN,NaN,True
725,cases,2021,year,CHFL,CHFL,all,agegroup_food,all,hus,29.0,...,0.33,NaN,22.3,NaN,3.1,NaN,NaN,NaN,NaN,True
726,cases,2021,year,CHFL,CHFL,all,agegroup_food,all,non-hus,918.0,...,10.46,NaN,849.7,NaN,96.9,NaN,NaN,NaN,NaN,True
727,cases,2022,year,CHFL,CHFL,all,agegroup_food,all,hus,24.0,...,0.27,NaN,23.7,NaN,2.0,NaN,NaN,NaN,NaN,True
728,cases,2022,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1181.0,...,13.34,NaN,926.7,NaN,98.0,NaN,NaN,NaN,NaN,True
729,cases,2023,year,CHFL,CHFL,all,agegroup_food,all,hus,22.0,...,0.24,NaN,25.0,NaN,1.8,NaN,NaN,NaN,NaN,True
730,cases,2023,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1217.0,...,13.52,NaN,1105.3,NaN,98.2,NaN,NaN,NaN,NaN,True
731,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,hus,24.0,...,0.26,NaN,23.3,NaN,1.7,NaN,NaN,NaN,NaN,True
732,cases,2024,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1368.0,...,15.05,NaN,1255.3,NaN,98.3,NaN,NaN,NaN,NaN,True
733,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,hus,23.0,...,0.25,NaN,23.0,NaN,1.6,NaN,NaN,NaN,NaN,True
734,cases,2025,year,CHFL,CHFL,all,agegroup_food,all,non-hus,1423.0,...,15.65,NaN,1336.0,NaN,98.4,NaN,NaN,NaN,NaN,True

In [23]:
col_selection_types = ["valueCategory", "temporal", "type", "value", "prct"]
col_selection_types

['valueCategory', 'temporal', 'type', 'value', 'prct']

In [24]:
data_types = data_types[col_selection_types]
data_types

    valueCategory temporal     type   value  prct
709         cases     2013      hus    11.0  13.3
710         cases     2013  non-hus    72.0  86.7
711         cases     2014      hus    11.0   8.8
712         cases     2014  non-hus   114.0  91.2
713         cases     2015      hus    14.0   4.5
714         cases     2015  non-hus   294.0  95.5
715         cases     2016      hus    16.0   3.1
716         cases     2016  non-hus   494.0  96.9
717         cases     2017      hus    19.0   2.6
718         cases     2017  non-hus   702.0  97.4
719         cases     2018      hus    23.0   2.6
720         cases     2018  non-hus   855.0  97.4
721         cases     2019      hus    20.0   2.1
722         cases     2019  non-hus   950.0  97.9
723         cases     2020      hus    18.0   2.6
724         cases     2020  non-hus   681.0  97.4
725         cases     2021      hus    29.0   3.1
726         cases     2021  non-hus   918.0  96.9
727         cases     2022      hus    24.0   2.0
728         cases     2022  non-hus  1181.0  98.0
729         cases     2023      hus    22.0   1.8
730         cases     2023  non-hus  1217.0  98.2
731         cases     2024      hus    24.0   1.7
732         cases     2024  non-hus  1368.0  98.3
733         cases     2025      hus    23.0   1.6
734         cases     2025  non-hus  1423.0  98.4

In [25]:
# Exportieren des Datensatzes
# data_types.to_csv("./export/reduziert_für_viz/ehec/data_ehec_types.csv", index=False)

### Historische Entwicklung & Saisonalität
Variablen:
* valueCategory = "cases"
* temporal
* temporal_type = "month"
* value

--> Einzelner Datensatz pro Jahr

--> Trennen Monate & Jahre

In [26]:
data_temp = data.copy()
data_temp

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
766,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,male,all,3928.0,...,NaN,NaN,NaN,NaN,44.3,NaN,NaN,NaN,NaN,True
767,cases_10y_cumsum,2024,year,CHFL,CHFL,all,agegroup_food,unknown,all,10.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True
768,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,female,all,5569.0,...,NaN,NaN,NaN,NaN,55.7,NaN,NaN,NaN,NaN,True
769,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,male,all,4427.0,...,NaN,NaN,NaN,NaN,44.2,NaN,NaN,NaN,NaN,True
770,cases_10y_cumsum,2025,year,CHFL,CHFL,all,agegroup_food,unknown,all,11.0,...,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,True

In [27]:
data_temp = data_temp[data_temp["valueCategory"]== "cases"]
data_temp = data_temp[data_temp["temporal_type"]== "month"]
data_temp

,valueCategory,temporal,temporal_type,georegion,georegion_type,agegroup,agegroup_type,sex,type,value,...,incValue,valueYearCumSum,valueMean3y,trend,prct,deltaValue,deltaIncValue,incValuePrctChange,valueMean5y,dataComplete
0,cases,2013-M01,month,CHFL,CHFL,all,agegroup_food,all,all,2.0,...,0.02,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,cases,2013-M02,month,CHFL,CHFL,all,agegroup_food,all,all,0.0,...,0.00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,cases,2013-M03,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,cases,2013-M04,month,CHFL,CHFL,all,agegroup_food,all,all,8.0,...,0.10,16.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
4,cases,2013-M05,month,CHFL,CHFL,all,agegroup_food,all,all,6.0,...,0.07,22.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,cases,2026-M04,month,CHFL,CHFL,all,agegroup_food,all,all,112.0,...,1.23,406.0,NaN,stagnant,NaN,NaN,NaN,NaN,NaN,True
160,cases,2026-M05,month,CHFL,CHFL,all,agegroup_food,all,all,138.0,...,1.52,544.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
161,cases,2026-M06,month,CHFL,CHFL,all,agegroup_food,all,all,165.0,...,1.81,709.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
162,cases,2026-M07,month,CHFL,CHFL,all,agegroup_food,all,all,267.0,...,2.94,976.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True
163,cases,2026-M08,month,CHFL,CHFL,all,agegroup_food,all,all,261.0,...,2.87,1237.0,NaN,rising,NaN,NaN,NaN,NaN,NaN,True

In [28]:
col_selection_temp = ["valueCategory", "temporal", "value"]
col_selection_temp

['valueCategory', 'temporal', 'value']

In [29]:
data_temp = data_temp[col_selection_temp]
data_temp

    valueCategory  temporal  value
0           cases  2013-M01    2.0
1           cases  2013-M02    0.0
2           cases  2013-M03    6.0
3           cases  2013-M04    8.0
4           cases  2013-M05    6.0
..            ...       ...    ...
159         cases  2026-M04  112.0
160         cases  2026-M05  138.0
161         cases  2026-M06  165.0
162         cases  2026-M07  267.0
163         cases  2026-M08  261.0

[164 rows x 3 columns]

In [30]:
data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
data_temp["year"] = data_temp["year"].astype(int)
data_temp["month"] = data_temp["month"].astype(int)
data_temp

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_53627/2264127337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_53627/2264127337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp[["year", "month"]] = data_temp["temporal"].str.extract(r"(\d{4})-M(\d+)")
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_53627/2264127337.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["year"] = data_temp["year"].astype(int)
/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_53627/2264127337.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["month"] = data_temp["month"].astype(int)

    valueCategory  temporal  value  year  month
0           cases  2013-M01    2.0  2013      1
1           cases  2013-M02    0.0  2013      2
2           cases  2013-M03    6.0  2013      3
3           cases  2013-M04    8.0  2013      4
4           cases  2013-M05    6.0  2013      5
..            ...       ...    ...   ...    ...
159         cases  2026-M04  112.0  2026      4
160         cases  2026-M05  138.0  2026      5
161         cases  2026-M06  165.0  2026      6
162         cases  2026-M07  267.0  2026      7
163         cases  2026-M08  261.0  2026      8

[164 rows x 5 columns]

In [31]:
data_temp_2 = data_temp.copy()
data_temp_2 = data_temp_2[data_temp_2["year"] == 2013]
data_temp_2

   valueCategory  temporal  value  year  month
0          cases  2013-M01    2.0  2013      1
1          cases  2013-M02    0.0  2013      2
2          cases  2013-M03    6.0  2013      3
3          cases  2013-M04    8.0  2013      4
4          cases  2013-M05    6.0  2013      5
5          cases  2013-M06    5.0  2013      6
6          cases  2013-M07   11.0  2013      7
7          cases  2013-M08   22.0  2013      8
8          cases  2013-M09    4.0  2013      9
9          cases  2013-M10    5.0  2013     10
10         cases  2013-M11    6.0  2013     11
11         cases  2013-M12    8.0  2013     12

In [32]:
# Vergleich der Monate (Saisonalität)
data_temp["value_cat"] = (
    data_temp.groupby("year")["value"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=4,
            labels=[1, 2, 3, 4]
        )
    )
)

data_temp

/var/folders/wr/rgnzqf8x4w501ytwkhks5qfw0000gn/T/ipykernel_53627/4145613601.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_temp["value_cat"] = (

    valueCategory  temporal  value  year  month value_cat
0           cases  2013-M01    2.0  2013      1         1
1           cases  2013-M02    0.0  2013      2         1
2           cases  2013-M03    6.0  2013      3         2
3           cases  2013-M04    8.0  2013      4         2
4           cases  2013-M05    6.0  2013      5         2
..            ...       ...    ...   ...    ...       ...
159         cases  2026-M04  112.0  2026      4         1
160         cases  2026-M05  138.0  2026      5         2
161         cases  2026-M06  165.0  2026      6         2
162         cases  2026-M07  267.0  2026      7         4
163         cases  2026-M08  261.0  2026      8         4

[164 rows x 6 columns]

In [33]:
# Exportieren des Datensatzes
# data_temp.to_csv("./export/reduziert_für_viz/ehec/data_ehec_historisch.csv", index=False)