In [1]:
# Importieren der Libraries

# Daten-Analyse
import pandas as pd

# Daten-Visualisierung
import altair as alt

In [3]:
data = pd.read_csv("data/test.csv")

data

    valueCategory  temporal  value     year  month value_cat
0           cases  2013-M01   87.0     2013      1         1
1           cases  2013-M02   76.0     2013      2         1
2           cases  2013-M03   63.0     2013      3         1
3           cases  2013-M04   92.0     2013      4         1
4           cases  2013-M05   88.0     2013      5         1
..            ...       ...    ...      ...    ...       ...
171        median       NaN  320.0   median      8       NaN
172        median       NaN  220.0   median      9       Nan
173        median       NaN  190.0   median     10       Nan
174        median       NaN  118.0   median     11       NaN
175        median       NaN   88.0   median     12       Nan

[176 rows x 6 columns]

In [4]:
# Vergleich der Monate (Saisonalität)
data["value_cat"] = (
    data.groupby("year")["value"]
    .transform(
        lambda values: pd.cut(
            values,
            bins=4,
            labels=[1, 2, 3, 4]
        )
    )
)

data

    valueCategory  temporal  value     year  month value_cat
0           cases  2013-M01   87.0     2013      1         1
1           cases  2013-M02   76.0     2013      2         1
2           cases  2013-M03   63.0     2013      3         1
3           cases  2013-M04   92.0     2013      4         1
4           cases  2013-M05   88.0     2013      5         1
..            ...       ...    ...      ...    ...       ...
171        median       NaN  320.0   median      8         4
172        median       NaN  220.0   median      9         3
173        median       NaN  190.0   median     10         2
174        median       NaN  118.0   median     11         1
175        median       NaN   88.0   median     12         1

[176 rows x 6 columns]